<%@ taglib uri="//java.sun.com/jsp/jstl/core" prefix="c" %><!-- IMPORTANT: For demo purposes only. This is an un-editable inlcude. All markup for pageoptions will be generated by CMS editorial options in the appropriate localtions. -->
<div class="pageoptionsContainer languageOptions languageOptionsOff">
	<span id="po-language-label" class="select-label">Language:</span>
	<div id="po-language" class="languages pageoptions pull-right">
		<div class="select-box"><a href="#">English</a><span class="icon-angle-down pull-right poarrow"></span></div>
		<ul class="drop-down" aria-labelledby="po-language-label">
			<li><a class="no-link" href="//www.cdc.gov">&#20013;&#25991; Chinese</a></li>
			<li><a class="no-link" href="//www.cdc.gov">Deutsch (German)</a></li>
			<li><a class="no-link" href="//www.cdc.gov">Espa&#241;ol (Spanish)</a></li>
			<li><a class="no-link" href="//www.cdc.gov">Fran&#231;ais (French)</a></li>
			<li><a class="no-link" href="//www.cdc.gov">Italiano (Italian)</a></li>
			<li><a class="no-link" href="//www.cdc.gov">&#54620;&#44397;&#50612; (Korean)</a></li>
			<li><a class="no-link" href="//www.cdc.gov">&#1056;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081; (Russian)</a></li>
			<li><a class="no-link" href="//www.cdc.gov">Ti&#7869;ng Vi&#7879;t (Vietnamese)</a></li>
		</ul>
	</div>
</div>