
using System;
using System.Collections.Generic;
using System.Linq;

namespace mmria.case_version.v1;

public sealed partial class mmria_case
{


    public string? GetSS_String(string path)
    {
        string? result = path.ToLower() switch
        {
         "version" => this.version,
         "created_by" => this.created_by,
         "last_updated_by" => this.last_updated_by,
         "last_checked_out_by" => this.last_checked_out_by,
         "host_state" => this.host_state,
         "addquarter" => this.addquarter,
         "cmpquarter" => this.cmpquarter,
         "home_record/first_name" => this.home_record.first_name,
         "home_record/middle_name" => this.home_record.middle_name,
         "home_record/last_name" => this.home_record.last_name,
         "home_record/state_of_death_record" => this.home_record.state_of_death_record,
         "home_record/record_id" => this.home_record.record_id,
         "home_record/agency_case_id" => this.home_record.agency_case_id,
         "home_record/specify_other_multiple_sources" => this.home_record.specify_other_multiple_sources,
         "home_record/primary_abstractor" => this.home_record.primary_abstractor,
         "home_record/jurisdiction_id" => this.home_record.jurisdiction_id,
         "home_record/overall_assessment_of_timing_of_death/hr_prg_outcome_othsp" => this.home_record.overall_assessment_of_timing_of_death.hr_prg_outcome_othsp,
         "home_record/automated_vitals_group/vital_report" => this.home_record.automated_vitals_group.vital_report,
         "home_record/automated_vitals_group/vro_status" => this.home_record.automated_vitals_group.vro_status,
         "home_record/automated_vitals_group/import_date" => this.home_record.automated_vitals_group.import_date,
         "death_certificate/certificate_identification/local_file_number" => this.death_certificate.certificate_identification.local_file_number,
         "death_certificate/certificate_identification/state_file_number" => this.death_certificate.certificate_identification.state_file_number,
         "death_certificate/certificate_identification/dmaiden" => this.death_certificate.certificate_identification.dmaiden,
         "death_certificate/place_of_last_residence/street" => this.death_certificate.place_of_last_residence.street,
         "death_certificate/place_of_last_residence/apartment" => this.death_certificate.place_of_last_residence.apartment,
         "death_certificate/place_of_last_residence/city" => this.death_certificate.place_of_last_residence.city,
         "death_certificate/place_of_last_residence/state" => this.death_certificate.place_of_last_residence.state,
         "death_certificate/place_of_last_residence/country_of_last_residence" => this.death_certificate.place_of_last_residence.country_of_last_residence,
         "death_certificate/place_of_last_residence/zip_code" => this.death_certificate.place_of_last_residence.zip_code,
         "death_certificate/place_of_last_residence/county" => this.death_certificate.place_of_last_residence.county,
         "death_certificate/place_of_last_residence/feature_matching_geography_type" => this.death_certificate.place_of_last_residence.feature_matching_geography_type,
         "death_certificate/place_of_last_residence/latitude" => this.death_certificate.place_of_last_residence.latitude,
         "death_certificate/place_of_last_residence/longitude" => this.death_certificate.place_of_last_residence.longitude,
         "death_certificate/place_of_last_residence/naaccr_gis_coordinate_quality_code" => this.death_certificate.place_of_last_residence.naaccr_gis_coordinate_quality_code,
         "death_certificate/place_of_last_residence/naaccr_gis_coordinate_quality_type" => this.death_certificate.place_of_last_residence.naaccr_gis_coordinate_quality_type,
         "death_certificate/place_of_last_residence/naaccr_census_tract_certainty_code" => this.death_certificate.place_of_last_residence.naaccr_census_tract_certainty_code,
         "death_certificate/place_of_last_residence/naaccr_census_tract_certainty_type" => this.death_certificate.place_of_last_residence.naaccr_census_tract_certainty_type,
         "death_certificate/place_of_last_residence/state_county_fips" => this.death_certificate.place_of_last_residence.state_county_fips,
         "death_certificate/place_of_last_residence/census_state_fips" => this.death_certificate.place_of_last_residence.census_state_fips,
         "death_certificate/place_of_last_residence/census_county_fips" => this.death_certificate.place_of_last_residence.census_county_fips,
         "death_certificate/place_of_last_residence/census_tract_fips" => this.death_certificate.place_of_last_residence.census_tract_fips,
         "death_certificate/place_of_last_residence/urban_status" => this.death_certificate.place_of_last_residence.urban_status,
         "death_certificate/place_of_last_residence/census_met_div_fips" => this.death_certificate.place_of_last_residence.census_met_div_fips,
         "death_certificate/place_of_last_residence/census_cbsa_fips" => this.death_certificate.place_of_last_residence.census_cbsa_fips,
         "death_certificate/place_of_last_residence/census_cbsa_micro" => this.death_certificate.place_of_last_residence.census_cbsa_micro,
         "death_certificate/demographics/city_of_birth" => this.death_certificate.demographics.city_of_birth,
         "death_certificate/demographics/state_of_birth" => this.death_certificate.demographics.state_of_birth,
         "death_certificate/demographics/country_of_birth" => this.death_certificate.demographics.country_of_birth,
         "death_certificate/demographics/primary_occupation" => this.death_certificate.demographics.primary_occupation,
         "death_certificate/demographics/occupation_business_industry" => this.death_certificate.demographics.occupation_business_industry,
         "death_certificate/demographics/is_of_hispanic_origin_other_specify" => this.death_certificate.demographics.is_of_hispanic_origin_other_specify,
         "death_certificate/demographics/dc_m_industry_code_1" => this.death_certificate.demographics.dc_m_industry_code_1,
         "death_certificate/demographics/dc_m_industry_code_2" => this.death_certificate.demographics.dc_m_industry_code_2,
         "death_certificate/demographics/dc_m_industry_code_3" => this.death_certificate.demographics.dc_m_industry_code_3,
         "death_certificate/demographics/dc_m_occupation_code_1" => this.death_certificate.demographics.dc_m_occupation_code_1,
         "death_certificate/demographics/dc_m_occupation_code_2" => this.death_certificate.demographics.dc_m_occupation_code_2,
         "death_certificate/demographics/dc_m_occupation_code_3" => this.death_certificate.demographics.dc_m_occupation_code_3,
         "death_certificate/citizen_of_what_country" => this.death_certificate.citizen_of_what_country,
         "death_certificate/race/other_race" => this.death_certificate.race.other_race,
         "death_certificate/race/other_asian" => this.death_certificate.race.other_asian,
         "death_certificate/race/other_pacific_islander" => this.death_certificate.race.other_pacific_islander,
         "death_certificate/race/principle_tribe" => this.death_certificate.race.principle_tribe,
         "death_certificate/injury_associated_information/place_of_injury" => this.death_certificate.injury_associated_information.place_of_injury,
         "death_certificate/injury_associated_information/transport_related_other_specify" => this.death_certificate.injury_associated_information.transport_related_other_specify,
         "death_certificate/address_of_injury/street" => this.death_certificate.address_of_injury.street,
         "death_certificate/address_of_injury/apartment" => this.death_certificate.address_of_injury.apartment,
         "death_certificate/address_of_injury/city" => this.death_certificate.address_of_injury.city,
         "death_certificate/address_of_injury/state" => this.death_certificate.address_of_injury.state,
         "death_certificate/address_of_injury/zip_code" => this.death_certificate.address_of_injury.zip_code,
         "death_certificate/address_of_injury/county" => this.death_certificate.address_of_injury.county,
         "death_certificate/address_of_injury/feature_matching_geography_type" => this.death_certificate.address_of_injury.feature_matching_geography_type,
         "death_certificate/address_of_injury/latitude" => this.death_certificate.address_of_injury.latitude,
         "death_certificate/address_of_injury/longitude" => this.death_certificate.address_of_injury.longitude,
         "death_certificate/address_of_injury/naaccr_gis_coordinate_quality_code" => this.death_certificate.address_of_injury.naaccr_gis_coordinate_quality_code,
         "death_certificate/address_of_injury/naaccr_gis_coordinate_quality_type" => this.death_certificate.address_of_injury.naaccr_gis_coordinate_quality_type,
         "death_certificate/address_of_injury/naaccr_census_tract_certainty_code" => this.death_certificate.address_of_injury.naaccr_census_tract_certainty_code,
         "death_certificate/address_of_injury/naaccr_census_tract_certainty_type" => this.death_certificate.address_of_injury.naaccr_census_tract_certainty_type,
         "death_certificate/address_of_injury/state_county_fips" => this.death_certificate.address_of_injury.state_county_fips,
         "death_certificate/address_of_injury/census_state_fips" => this.death_certificate.address_of_injury.census_state_fips,
         "death_certificate/address_of_injury/census_county_fips" => this.death_certificate.address_of_injury.census_county_fips,
         "death_certificate/address_of_injury/census_tract_fips" => this.death_certificate.address_of_injury.census_tract_fips,
         "death_certificate/address_of_injury/urban_status" => this.death_certificate.address_of_injury.urban_status,
         "death_certificate/address_of_injury/census_met_div_fips" => this.death_certificate.address_of_injury.census_met_div_fips,
         "death_certificate/address_of_injury/census_cbsa_fips" => this.death_certificate.address_of_injury.census_cbsa_fips,
         "death_certificate/address_of_injury/census_cbsa_micro" => this.death_certificate.address_of_injury.census_cbsa_micro,
         "death_certificate/death_information/other_death_outside_of_hospital" => this.death_certificate.death_information.other_death_outside_of_hospital,
         "death_certificate/address_of_death/place_of_death" => this.death_certificate.address_of_death.place_of_death,
         "death_certificate/address_of_death/street" => this.death_certificate.address_of_death.street,
         "death_certificate/address_of_death/apartment" => this.death_certificate.address_of_death.apartment,
         "death_certificate/address_of_death/city" => this.death_certificate.address_of_death.city,
         "death_certificate/address_of_death/state" => this.death_certificate.address_of_death.state,
         "death_certificate/address_of_death/zip_code" => this.death_certificate.address_of_death.zip_code,
         "death_certificate/address_of_death/county" => this.death_certificate.address_of_death.county,
         "death_certificate/address_of_death/feature_matching_geography_type" => this.death_certificate.address_of_death.feature_matching_geography_type,
         "death_certificate/address_of_death/latitude" => this.death_certificate.address_of_death.latitude,
         "death_certificate/address_of_death/longitude" => this.death_certificate.address_of_death.longitude,
         "death_certificate/address_of_death/naaccr_gis_coordinate_quality_code" => this.death_certificate.address_of_death.naaccr_gis_coordinate_quality_code,
         "death_certificate/address_of_death/naaccr_gis_coordinate_quality_type" => this.death_certificate.address_of_death.naaccr_gis_coordinate_quality_type,
         "death_certificate/address_of_death/naaccr_census_tract_certainty_code" => this.death_certificate.address_of_death.naaccr_census_tract_certainty_code,
         "death_certificate/address_of_death/naaccr_census_tract_certainty_type" => this.death_certificate.address_of_death.naaccr_census_tract_certainty_type,
         "death_certificate/address_of_death/state_county_fips" => this.death_certificate.address_of_death.state_county_fips,
         "death_certificate/address_of_death/census_state_fips" => this.death_certificate.address_of_death.census_state_fips,
         "death_certificate/address_of_death/census_county_fips" => this.death_certificate.address_of_death.census_county_fips,
         "death_certificate/address_of_death/census_tract_fips" => this.death_certificate.address_of_death.census_tract_fips,
         "death_certificate/address_of_death/urban_status" => this.death_certificate.address_of_death.urban_status,
         "death_certificate/address_of_death/census_met_div_fips" => this.death_certificate.address_of_death.census_met_div_fips,
         "death_certificate/address_of_death/census_cbsa_fips" => this.death_certificate.address_of_death.census_cbsa_fips,
         "death_certificate/address_of_death/census_cbsa_micro" => this.death_certificate.address_of_death.census_cbsa_micro,
         "death_certificate/reviewer_note" => this.death_certificate.reviewer_note,
         "death_certificate/vitals_import_group/vital_summary_text" => this.death_certificate.vitals_import_group.vital_summary_text,
         "death_certificate/vitals_import_group/cod1a" => this.death_certificate.vitals_import_group.cod1a,
         "death_certificate/vitals_import_group/interval1a" => this.death_certificate.vitals_import_group.interval1a,
         "death_certificate/vitals_import_group/cod1b" => this.death_certificate.vitals_import_group.cod1b,
         "death_certificate/vitals_import_group/interval1b" => this.death_certificate.vitals_import_group.interval1b,
         "death_certificate/vitals_import_group/cod1c" => this.death_certificate.vitals_import_group.cod1c,
         "death_certificate/vitals_import_group/interval1c" => this.death_certificate.vitals_import_group.interval1c,
         "death_certificate/vitals_import_group/cod1d" => this.death_certificate.vitals_import_group.cod1d,
         "death_certificate/vitals_import_group/interfval1d" => this.death_certificate.vitals_import_group.interfval1d,
         "death_certificate/vitals_import_group/othercondition" => this.death_certificate.vitals_import_group.othercondition,
         "death_certificate/vitals_import_group/man_uc" => this.death_certificate.vitals_import_group.man_uc,
         "death_certificate/vitals_import_group/acme_uc" => this.death_certificate.vitals_import_group.acme_uc,
         "death_certificate/vitals_import_group/eac" => this.death_certificate.vitals_import_group.eac,
         "death_certificate/vitals_import_group/rac" => this.death_certificate.vitals_import_group.rac,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/other_maternal_level_of_care" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.other_maternal_level_of_care,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/facility_npi_number" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.facility_npi_number,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/facility_name" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.facility_name,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/other_attendant_type" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.other_attendant_type,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/attendant_npi" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.attendant_npi,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/transferred_from_where" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.transferred_from_where,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/street" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.street,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/apartment" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.apartment,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/city" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.city,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/state" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.state,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/zip_code" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.zip_code,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/county" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.county,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/latitude" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.latitude,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/longitude" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.longitude,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/feature_matching_geography_type" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.feature_matching_geography_type,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/naaccr_gis_coordinate_quality_code" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.naaccr_gis_coordinate_quality_code,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/naaccr_gis_coordinate_quality_type" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.naaccr_gis_coordinate_quality_type,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/naaccr_census_tract_certainty_code" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.naaccr_census_tract_certainty_code,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/naaccr_census_tract_certainty_type" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.naaccr_census_tract_certainty_type,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/urban_status" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.urban_status,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/state_county_fips" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.state_county_fips,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/census_state_fips" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.census_state_fips,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/census_county_fips" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.census_county_fips,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/census_tract_fips" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.census_tract_fips,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/census_met_div_fips" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.census_met_div_fips,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/census_cbsa_fips" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.census_cbsa_fips,
         "birth_fetal_death_certificate_parent/facility_of_delivery_location/census_cbsa_micro" => this.birth_fetal_death_certificate_parent.facility_of_delivery_location.census_cbsa_micro,
         "birth_fetal_death_certificate_parent/demographic_of_father/city_of_birth" => this.birth_fetal_death_certificate_parent.demographic_of_father.city_of_birth,
         "birth_fetal_death_certificate_parent/demographic_of_father/state_of_birth" => this.birth_fetal_death_certificate_parent.demographic_of_father.state_of_birth,
         "birth_fetal_death_certificate_parent/demographic_of_father/father_country_of_birth" => this.birth_fetal_death_certificate_parent.demographic_of_father.father_country_of_birth,
         "birth_fetal_death_certificate_parent/demographic_of_father/primary_occupation" => this.birth_fetal_death_certificate_parent.demographic_of_father.primary_occupation,
         "birth_fetal_death_certificate_parent/demographic_of_father/occupation_business_industry" => this.birth_fetal_death_certificate_parent.demographic_of_father.occupation_business_industry,
         "birth_fetal_death_certificate_parent/demographic_of_father/is_father_of_hispanic_origin_other_specify" => this.birth_fetal_death_certificate_parent.demographic_of_father.is_father_of_hispanic_origin_other_specify,
         "birth_fetal_death_certificate_parent/demographic_of_father/race/other_race" => this.birth_fetal_death_certificate_parent.demographic_of_father.race.other_race,
         "birth_fetal_death_certificate_parent/demographic_of_father/race/other_asian" => this.birth_fetal_death_certificate_parent.demographic_of_father.race.other_asian,
         "birth_fetal_death_certificate_parent/demographic_of_father/race/other_pacific_islander" => this.birth_fetal_death_certificate_parent.demographic_of_father.race.other_pacific_islander,
         "birth_fetal_death_certificate_parent/demographic_of_father/race/principle_tribe" => this.birth_fetal_death_certificate_parent.demographic_of_father.race.principle_tribe,
         "birth_fetal_death_certificate_parent/demographic_of_father/race/omb_race_recode" => this.birth_fetal_death_certificate_parent.demographic_of_father.race.omb_race_recode,
         "birth_fetal_death_certificate_parent/demographic_of_father/bcdcp_f_industry_code_1" => this.birth_fetal_death_certificate_parent.demographic_of_father.bcdcp_f_industry_code_1,
         "birth_fetal_death_certificate_parent/demographic_of_father/bcdcp_f_industry_code_2" => this.birth_fetal_death_certificate_parent.demographic_of_father.bcdcp_f_industry_code_2,
         "birth_fetal_death_certificate_parent/demographic_of_father/bcdcp_f_industry_code_3" => this.birth_fetal_death_certificate_parent.demographic_of_father.bcdcp_f_industry_code_3,
         "birth_fetal_death_certificate_parent/demographic_of_father/bcdcp_f_occupation_code_1" => this.birth_fetal_death_certificate_parent.demographic_of_father.bcdcp_f_occupation_code_1,
         "birth_fetal_death_certificate_parent/demographic_of_father/bcdcp_f_occupation_code_2" => this.birth_fetal_death_certificate_parent.demographic_of_father.bcdcp_f_occupation_code_2,
         "birth_fetal_death_certificate_parent/demographic_of_father/bcdcp_f_occupation_code_3" => this.birth_fetal_death_certificate_parent.demographic_of_father.bcdcp_f_occupation_code_3,
         "birth_fetal_death_certificate_parent/record_identification/first_name" => this.birth_fetal_death_certificate_parent.record_identification.first_name,
         "birth_fetal_death_certificate_parent/record_identification/middle_name" => this.birth_fetal_death_certificate_parent.record_identification.middle_name,
         "birth_fetal_death_certificate_parent/record_identification/last_name" => this.birth_fetal_death_certificate_parent.record_identification.last_name,
         "birth_fetal_death_certificate_parent/record_identification/maiden_name" => this.birth_fetal_death_certificate_parent.record_identification.maiden_name,
         "birth_fetal_death_certificate_parent/record_identification/medical_record_number" => this.birth_fetal_death_certificate_parent.record_identification.medical_record_number,
         "birth_fetal_death_certificate_parent/demographic_of_mother/city_of_birth" => this.birth_fetal_death_certificate_parent.demographic_of_mother.city_of_birth,
         "birth_fetal_death_certificate_parent/demographic_of_mother/state_of_birth" => this.birth_fetal_death_certificate_parent.demographic_of_mother.state_of_birth,
         "birth_fetal_death_certificate_parent/demographic_of_mother/country_of_birth" => this.birth_fetal_death_certificate_parent.demographic_of_mother.country_of_birth,
         "birth_fetal_death_certificate_parent/demographic_of_mother/primary_occupation" => this.birth_fetal_death_certificate_parent.demographic_of_mother.primary_occupation,
         "birth_fetal_death_certificate_parent/demographic_of_mother/occupation_business_industry" => this.birth_fetal_death_certificate_parent.demographic_of_mother.occupation_business_industry,
         "birth_fetal_death_certificate_parent/demographic_of_mother/is_of_hispanic_origin_other_specify" => this.birth_fetal_death_certificate_parent.demographic_of_mother.is_of_hispanic_origin_other_specify,
         "birth_fetal_death_certificate_parent/demographic_of_mother/bcdcp_m_industry_code_1" => this.birth_fetal_death_certificate_parent.demographic_of_mother.bcdcp_m_industry_code_1,
         "birth_fetal_death_certificate_parent/demographic_of_mother/bcdcp_m_industry_code_2" => this.birth_fetal_death_certificate_parent.demographic_of_mother.bcdcp_m_industry_code_2,
         "birth_fetal_death_certificate_parent/demographic_of_mother/bcdcp_m_industry_code_3" => this.birth_fetal_death_certificate_parent.demographic_of_mother.bcdcp_m_industry_code_3,
         "birth_fetal_death_certificate_parent/demographic_of_mother/bcdcp_m_occupation_code_1" => this.birth_fetal_death_certificate_parent.demographic_of_mother.bcdcp_m_occupation_code_1,
         "birth_fetal_death_certificate_parent/demographic_of_mother/bcdcp_m_occupation_code_2" => this.birth_fetal_death_certificate_parent.demographic_of_mother.bcdcp_m_occupation_code_2,
         "birth_fetal_death_certificate_parent/demographic_of_mother/bcdcp_m_occupation_code_3" => this.birth_fetal_death_certificate_parent.demographic_of_mother.bcdcp_m_occupation_code_3,
         "birth_fetal_death_certificate_parent/location_of_residence/street" => this.birth_fetal_death_certificate_parent.location_of_residence.street,
         "birth_fetal_death_certificate_parent/location_of_residence/apartment" => this.birth_fetal_death_certificate_parent.location_of_residence.apartment,
         "birth_fetal_death_certificate_parent/location_of_residence/city" => this.birth_fetal_death_certificate_parent.location_of_residence.city,
         "birth_fetal_death_certificate_parent/location_of_residence/state" => this.birth_fetal_death_certificate_parent.location_of_residence.state,
         "birth_fetal_death_certificate_parent/location_of_residence/zip_code" => this.birth_fetal_death_certificate_parent.location_of_residence.zip_code,
         "birth_fetal_death_certificate_parent/location_of_residence/county" => this.birth_fetal_death_certificate_parent.location_of_residence.county,
         "birth_fetal_death_certificate_parent/location_of_residence/feature_matching_geography_type" => this.birth_fetal_death_certificate_parent.location_of_residence.feature_matching_geography_type,
         "birth_fetal_death_certificate_parent/location_of_residence/latitude" => this.birth_fetal_death_certificate_parent.location_of_residence.latitude,
         "birth_fetal_death_certificate_parent/location_of_residence/longitude" => this.birth_fetal_death_certificate_parent.location_of_residence.longitude,
         "birth_fetal_death_certificate_parent/location_of_residence/naaccr_gis_coordinate_quality_code" => this.birth_fetal_death_certificate_parent.location_of_residence.naaccr_gis_coordinate_quality_code,
         "birth_fetal_death_certificate_parent/location_of_residence/naaccr_gis_coordinate_quality_type" => this.birth_fetal_death_certificate_parent.location_of_residence.naaccr_gis_coordinate_quality_type,
         "birth_fetal_death_certificate_parent/location_of_residence/naaccr_census_tract_certainty_code" => this.birth_fetal_death_certificate_parent.location_of_residence.naaccr_census_tract_certainty_code,
         "birth_fetal_death_certificate_parent/location_of_residence/naaccr_census_tract_certainty_type" => this.birth_fetal_death_certificate_parent.location_of_residence.naaccr_census_tract_certainty_type,
         "birth_fetal_death_certificate_parent/location_of_residence/state_county_fips" => this.birth_fetal_death_certificate_parent.location_of_residence.state_county_fips,
         "birth_fetal_death_certificate_parent/location_of_residence/census_state_fips" => this.birth_fetal_death_certificate_parent.location_of_residence.census_state_fips,
         "birth_fetal_death_certificate_parent/location_of_residence/census_county_fips" => this.birth_fetal_death_certificate_parent.location_of_residence.census_county_fips,
         "birth_fetal_death_certificate_parent/location_of_residence/census_tract_fips" => this.birth_fetal_death_certificate_parent.location_of_residence.census_tract_fips,
         "birth_fetal_death_certificate_parent/location_of_residence/urban_status" => this.birth_fetal_death_certificate_parent.location_of_residence.urban_status,
         "birth_fetal_death_certificate_parent/location_of_residence/census_met_div_fips" => this.birth_fetal_death_certificate_parent.location_of_residence.census_met_div_fips,
         "birth_fetal_death_certificate_parent/location_of_residence/census_cbsa_fips" => this.birth_fetal_death_certificate_parent.location_of_residence.census_cbsa_fips,
         "birth_fetal_death_certificate_parent/location_of_residence/census_cbsa_micro" => this.birth_fetal_death_certificate_parent.location_of_residence.census_cbsa_micro,
         "birth_fetal_death_certificate_parent/race/other_race" => this.birth_fetal_death_certificate_parent.race.other_race,
         "birth_fetal_death_certificate_parent/race/other_asian" => this.birth_fetal_death_certificate_parent.race.other_asian,
         "birth_fetal_death_certificate_parent/race/other_pacific_islander" => this.birth_fetal_death_certificate_parent.race.other_pacific_islander,
         "birth_fetal_death_certificate_parent/race/principle_tribe" => this.birth_fetal_death_certificate_parent.race.principle_tribe,
         "birth_fetal_death_certificate_parent/race/omb_race_recode" => this.birth_fetal_death_certificate_parent.race.omb_race_recode,
         "birth_fetal_death_certificate_parent/pregnancy_history/pregnancy_interval" => this.birth_fetal_death_certificate_parent.pregnancy_history.pregnancy_interval,
         "birth_fetal_death_certificate_parent/prenatal_care/specify_if_greater_than_3" => this.birth_fetal_death_certificate_parent.prenatal_care.specify_if_greater_than_3,
         "birth_fetal_death_certificate_parent/prenatal_care/specify_other_payor" => this.birth_fetal_death_certificate_parent.prenatal_care.specify_other_payor,
         "birth_fetal_death_certificate_parent/specify_other_infection" => this.birth_fetal_death_certificate_parent.specify_other_infection,
         "birth_fetal_death_certificate_parent/reviewer_note" => this.birth_fetal_death_certificate_parent.reviewer_note,
         "cvs/cvs_used_other_sp" => this.cvs.cvs_used_other_sp,
         "cvs/reviewer_note" => this.cvs.reviewer_note,
         "social_and_environmental_profile/socio_economic_characteristics/source_of_income_other_specify" => this.social_and_environmental_profile.socio_economic_characteristics.source_of_income_other_specify,
         "social_and_environmental_profile/socio_economic_characteristics/employment_status_other_specify" => this.social_and_environmental_profile.socio_economic_characteristics.employment_status_other_specify,
         "social_and_environmental_profile/socio_economic_characteristics/occupation" => this.social_and_environmental_profile.socio_economic_characteristics.occupation,
         "social_and_environmental_profile/socio_economic_characteristics/religious_preference" => this.social_and_environmental_profile.socio_economic_characteristics.religious_preference,
         "social_and_environmental_profile/socio_economic_characteristics/country_of_birth" => this.social_and_environmental_profile.socio_economic_characteristics.country_of_birth,
         "social_and_environmental_profile/socio_economic_characteristics/sep_m_occupation_code_1" => this.social_and_environmental_profile.socio_economic_characteristics.sep_m_occupation_code_1,
         "social_and_environmental_profile/socio_economic_characteristics/sep_m_occupation_code_2" => this.social_and_environmental_profile.socio_economic_characteristics.sep_m_occupation_code_2,
         "social_and_environmental_profile/socio_economic_characteristics/sep_m_occupation_code_3" => this.social_and_environmental_profile.socio_economic_characteristics.sep_m_occupation_code_3,
         "social_and_environmental_profile/socio_economic_characteristics/sep_m_industry_code_1" => this.social_and_environmental_profile.socio_economic_characteristics.sep_m_industry_code_1,
         "social_and_environmental_profile/socio_economic_characteristics/sep_m_industry_code_2" => this.social_and_environmental_profile.socio_economic_characteristics.sep_m_industry_code_2,
         "social_and_environmental_profile/socio_economic_characteristics/sep_m_industry_code_3" => this.social_and_environmental_profile.socio_economic_characteristics.sep_m_industry_code_3,
         "social_and_environmental_profile/gender_identity/sep_genid_source_othersp" => this.social_and_environmental_profile.gender_identity.sep_genid_source_othersp,
         "social_and_environmental_profile/gender_identity/sep_genid_source_terms" => this.social_and_environmental_profile.gender_identity.sep_genid_source_terms,
         "social_and_environmental_profile/health_care_access/barriers_to_health_care_access_other_specify" => this.social_and_environmental_profile.health_care_access.barriers_to_health_care_access_other_specify,
         "social_and_environmental_profile/health_care_access/comments" => this.social_and_environmental_profile.health_care_access.comments,
         "social_and_environmental_profile/communications/barriers_to_communications_other_specify" => this.social_and_environmental_profile.communications.barriers_to_communications_other_specify,
         "social_and_environmental_profile/communications/comments" => this.social_and_environmental_profile.communications.comments,
         "social_and_environmental_profile/social_or_emotional_stress/specify_other_evidence_stress" => this.social_and_environmental_profile.social_or_emotional_stress.specify_other_evidence_stress,
         "social_and_environmental_profile/social_or_emotional_stress/explain_further" => this.social_and_environmental_profile.social_or_emotional_stress.explain_further,
         "social_and_environmental_profile/health_care_system/specify_other_reason" => this.social_and_environmental_profile.health_care_system.specify_other_reason,
         "social_and_environmental_profile/health_care_system/comments" => this.social_and_environmental_profile.health_care_system.comments,
         "social_and_environmental_profile/reviewer_note" => this.social_and_environmental_profile.reviewer_note,
         "autopsy_report/reporter_characteristics/other_specify" => this.autopsy_report.reporter_characteristics.other_specify,
         "autopsy_report/reporter_characteristics/jurisdiction" => this.autopsy_report.reporter_characteristics.jurisdiction,
         "autopsy_report/icd_code_version" => this.autopsy_report.icd_code_version,
         "autopsy_report/reviewer_note" => this.autopsy_report.reviewer_note,
         "prenatal/prenatal_care_record_no" => this.prenatal.prenatal_care_record_no,
         "prenatal/primary_prenatal_care_facility/other_place_type" => this.prenatal.primary_prenatal_care_facility.other_place_type,
         "prenatal/primary_prenatal_care_facility/specify_other_provider_type" => this.prenatal.primary_prenatal_care_facility.specify_other_provider_type,
         "prenatal/primary_prenatal_care_facility/other_payment_source" => this.prenatal.primary_prenatal_care_facility.other_payment_source,
         "prenatal/location_of_primary_prenatal_care_facility/street" => this.prenatal.location_of_primary_prenatal_care_facility.street,
         "prenatal/location_of_primary_prenatal_care_facility/apartment" => this.prenatal.location_of_primary_prenatal_care_facility.apartment,
         "prenatal/location_of_primary_prenatal_care_facility/city" => this.prenatal.location_of_primary_prenatal_care_facility.city,
         "prenatal/location_of_primary_prenatal_care_facility/state" => this.prenatal.location_of_primary_prenatal_care_facility.state,
         "prenatal/location_of_primary_prenatal_care_facility/zip_code" => this.prenatal.location_of_primary_prenatal_care_facility.zip_code,
         "prenatal/location_of_primary_prenatal_care_facility/county" => this.prenatal.location_of_primary_prenatal_care_facility.county,
         "prenatal/location_of_primary_prenatal_care_facility/feature_matching_geography_type" => this.prenatal.location_of_primary_prenatal_care_facility.feature_matching_geography_type,
         "prenatal/location_of_primary_prenatal_care_facility/latitude" => this.prenatal.location_of_primary_prenatal_care_facility.latitude,
         "prenatal/location_of_primary_prenatal_care_facility/longitude" => this.prenatal.location_of_primary_prenatal_care_facility.longitude,
         "prenatal/location_of_primary_prenatal_care_facility/naaccr_gis_coordinate_quality_code" => this.prenatal.location_of_primary_prenatal_care_facility.naaccr_gis_coordinate_quality_code,
         "prenatal/location_of_primary_prenatal_care_facility/naaccr_gis_coordinate_quality_type" => this.prenatal.location_of_primary_prenatal_care_facility.naaccr_gis_coordinate_quality_type,
         "prenatal/location_of_primary_prenatal_care_facility/naaccr_census_tract_certainty_code" => this.prenatal.location_of_primary_prenatal_care_facility.naaccr_census_tract_certainty_code,
         "prenatal/location_of_primary_prenatal_care_facility/naaccr_census_tract_certainty_type" => this.prenatal.location_of_primary_prenatal_care_facility.naaccr_census_tract_certainty_type,
         "prenatal/location_of_primary_prenatal_care_facility/state_county_fips" => this.prenatal.location_of_primary_prenatal_care_facility.state_county_fips,
         "prenatal/location_of_primary_prenatal_care_facility/census_state_fips" => this.prenatal.location_of_primary_prenatal_care_facility.census_state_fips,
         "prenatal/location_of_primary_prenatal_care_facility/census_county_fips" => this.prenatal.location_of_primary_prenatal_care_facility.census_county_fips,
         "prenatal/location_of_primary_prenatal_care_facility/census_tract_fips" => this.prenatal.location_of_primary_prenatal_care_facility.census_tract_fips,
         "prenatal/location_of_primary_prenatal_care_facility/urban_status" => this.prenatal.location_of_primary_prenatal_care_facility.urban_status,
         "prenatal/location_of_primary_prenatal_care_facility/census_met_div_fips" => this.prenatal.location_of_primary_prenatal_care_facility.census_met_div_fips,
         "prenatal/location_of_primary_prenatal_care_facility/census_cbsa_fips" => this.prenatal.location_of_primary_prenatal_care_facility.census_cbsa_fips,
         "prenatal/location_of_primary_prenatal_care_facility/census_cbsa_micro" => this.prenatal.location_of_primary_prenatal_care_facility.census_cbsa_micro,
         "prenatal/intendedenes/pi_wp_plann_sp" => this.prenatal.intendedenes.pi_wp_plann_sp,
         "prenatal/intendedenes/was_patient_using_birth_control_other_specify" => this.prenatal.intendedenes.was_patient_using_birth_control_other_specify,
         "prenatal/infertility_treatment/specify_other_art_type" => this.prenatal.infertility_treatment.specify_other_art_type,
         "prenatal/current_pregnancy/estimated_date_of_confinement/estimate_based_on_ultrasound" => this.prenatal.current_pregnancy.estimated_date_of_confinement.estimate_based_on_ultrasound,
         "prenatal/current_pregnancy/estimated_date_of_confinement/estimate_based_on_lmp" => this.prenatal.current_pregnancy.estimated_date_of_confinement.estimate_based_on_lmp,
         "prenatal/current_pregnancy/intended_birthing_facility" => this.prenatal.current_pregnancy.intended_birthing_facility,
         "prenatal/reviewer_note" => this.prenatal.reviewer_note,
         "mental_health_profile/other_prior_to_pregnancy" => this.mental_health_profile.other_prior_to_pregnancy,
         "mental_health_profile/other_during_pregnancy" => this.mental_health_profile.other_during_pregnancy,
         "mental_health_profile/other_after_pregnancy" => this.mental_health_profile.other_after_pregnancy,
         "mental_health_profile/reviewer_note" => this.mental_health_profile.reviewer_note,
         "case_narrative/case_opening_overview" => this.case_narrative.case_opening_overview,
         "committee_review/pmss_mm" => this.committee_review.pmss_mm,
         "committee_review/pmss_mm_secondary" => this.committee_review.pmss_mm_secondary,
         "committee_review/specify_other_means_fatal_injury" => this.committee_review.specify_other_means_fatal_injury,
         "committee_review/specify_other_relationship" => this.committee_review.specify_other_relationship,
         "committee_review/cr_add_recs" => this.committee_review.cr_add_recs,
         "committee_review/notes_about_key_circumstances_surrounding_death" => this.committee_review.notes_about_key_circumstances_surrounding_death,

            _ => null
        };
        
        return result;
    }

    public double? GetSS_Double(string path)
    {
        double? result = path.ToLower() switch
        {
         "home_record/date_of_death/month" => this.home_record.date_of_death.month,
         "home_record/date_of_death/day" => this.home_record.date_of_death.day,
         "home_record/date_of_death/year" => this.home_record.date_of_death.year,
         "home_record/case_status/overall_case_status" => this.home_record.case_status.overall_case_status,
         "home_record/overall_assessment_of_timing_of_death/abstrator_assigned_status" => this.home_record.overall_assessment_of_timing_of_death.abstrator_assigned_status,
         "home_record/overall_assessment_of_timing_of_death/number_of_days_after_end_of_pregnancey" => this.home_record.overall_assessment_of_timing_of_death.number_of_days_after_end_of_pregnancey,
         "home_record/overall_assessment_of_timing_of_death/hr_prg_outcome" => this.home_record.overall_assessment_of_timing_of_death.hr_prg_outcome,
         "home_record/case_progress_report/death_certificate" => this.home_record.case_progress_report.death_certificate,
         "home_record/case_progress_report/autopsy_report" => this.home_record.case_progress_report.autopsy_report,
         "home_record/case_progress_report/birth_certificate_parent_section" => this.home_record.case_progress_report.birth_certificate_parent_section,
         "home_record/case_progress_report/birth_certificate_infant_or_fetal_death_section" => this.home_record.case_progress_report.birth_certificate_infant_or_fetal_death_section,
         "home_record/case_progress_report/community_vital_signs" => this.home_record.case_progress_report.community_vital_signs,
         "home_record/case_progress_report/social_and_psychological_profile" => this.home_record.case_progress_report.social_and_psychological_profile,
         "home_record/case_progress_report/prenatal_care_record" => this.home_record.case_progress_report.prenatal_care_record,
         "home_record/case_progress_report/er_visits_and_hospitalizations" => this.home_record.case_progress_report.er_visits_and_hospitalizations,
         "home_record/case_progress_report/other_medical_visits" => this.home_record.case_progress_report.other_medical_visits,
         "home_record/case_progress_report/medical_transport" => this.home_record.case_progress_report.medical_transport,
         "home_record/case_progress_report/mental_health_profile" => this.home_record.case_progress_report.mental_health_profile,
         "home_record/case_progress_report/informant_interviews" => this.home_record.case_progress_report.informant_interviews,
         "home_record/case_progress_report/case_narrative" => this.home_record.case_progress_report.case_narrative,
         "home_record/case_progress_report/committe_review_worksheet" => this.home_record.case_progress_report.committe_review_worksheet,
         "home_record/automated_vitals_group/bc_det_match" => this.home_record.automated_vitals_group.bc_det_match,
         "home_record/automated_vitals_group/fdc_det_match" => this.home_record.automated_vitals_group.fdc_det_match,
         "home_record/automated_vitals_group/bc_prob_match" => this.home_record.automated_vitals_group.bc_prob_match,
         "home_record/automated_vitals_group/fdc_prob_match" => this.home_record.automated_vitals_group.fdc_prob_match,
         "home_record/automated_vitals_group/icd10_match" => this.home_record.automated_vitals_group.icd10_match,
         "home_record/automated_vitals_group/pregcb_match" => this.home_record.automated_vitals_group.pregcb_match,
         "home_record/automated_vitals_group/literalcod_match" => this.home_record.automated_vitals_group.literalcod_match,
         "death_certificate/demographics/date_of_birth/month" => this.death_certificate.demographics.date_of_birth.month,
         "death_certificate/demographics/date_of_birth/day" => this.death_certificate.demographics.date_of_birth.day,
         "death_certificate/demographics/date_of_birth/year" => this.death_certificate.demographics.date_of_birth.year,
         "death_certificate/demographics/age" => this.death_certificate.demographics.age,
         "death_certificate/demographics/age_on_death_certificate" => this.death_certificate.demographics.age_on_death_certificate,
         "death_certificate/demographics/marital_status" => this.death_certificate.demographics.marital_status,
         "death_certificate/demographics/ever_in_us_armed_forces" => this.death_certificate.demographics.ever_in_us_armed_forces,
         "death_certificate/demographics/is_of_hispanic_origin" => this.death_certificate.demographics.is_of_hispanic_origin,
         "death_certificate/demographics/education_level" => this.death_certificate.demographics.education_level,
         "death_certificate/race/omb_race_recode" => this.death_certificate.race.omb_race_recode,
         "death_certificate/injury_associated_information/date_of_injury/month" => this.death_certificate.injury_associated_information.date_of_injury.month,
         "death_certificate/injury_associated_information/date_of_injury/day" => this.death_certificate.injury_associated_information.date_of_injury.day,
         "death_certificate/injury_associated_information/date_of_injury/year" => this.death_certificate.injury_associated_information.date_of_injury.year,
         "death_certificate/injury_associated_information/was_injury_at_work" => this.death_certificate.injury_associated_information.was_injury_at_work,
         "death_certificate/injury_associated_information/transportation_related_injury" => this.death_certificate.injury_associated_information.transportation_related_injury,
         "death_certificate/injury_associated_information/were_seat_belts_in_use" => this.death_certificate.injury_associated_information.were_seat_belts_in_use,
         "death_certificate/death_information/death_occured_in_hospital" => this.death_certificate.death_information.death_occured_in_hospital,
         "death_certificate/death_information/death_outside_of_hospital" => this.death_certificate.death_information.death_outside_of_hospital,
         "death_certificate/death_information/manner_of_death" => this.death_certificate.death_information.manner_of_death,
         "death_certificate/death_information/was_autopsy_performed" => this.death_certificate.death_information.was_autopsy_performed,
         "death_certificate/death_information/was_autopsy_used_for_death_coding" => this.death_certificate.death_information.was_autopsy_used_for_death_coding,
         "death_certificate/death_information/pregnancy_status" => this.death_certificate.death_information.pregnancy_status,
         "death_certificate/death_information/did_tobacco_contribute_to_death" => this.death_certificate.death_information.did_tobacco_contribute_to_death,
         "death_certificate/address_of_death/estimated_death_distance_from_residence" => this.death_certificate.address_of_death.estimated_death_distance_from_residence,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/date_of_delivery/month" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.date_of_delivery.month,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/date_of_delivery/day" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.date_of_delivery.day,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/date_of_delivery/year" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.date_of_delivery.year,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/type_of_place" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.type_of_place,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/was_home_delivery_planned" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.was_home_delivery_planned,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/maternal_level_of_care" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.maternal_level_of_care,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/attendant_type" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.attendant_type,
         "birth_fetal_death_certificate_parent/facility_of_delivery_demographics/was_mother_transferred" => this.birth_fetal_death_certificate_parent.facility_of_delivery_demographics.was_mother_transferred,
         "birth_fetal_death_certificate_parent/demographic_of_father/date_of_birth/month" => this.birth_fetal_death_certificate_parent.demographic_of_father.date_of_birth.month,
         "birth_fetal_death_certificate_parent/demographic_of_father/date_of_birth/year" => this.birth_fetal_death_certificate_parent.demographic_of_father.date_of_birth.year,
         "birth_fetal_death_certificate_parent/demographic_of_father/age" => this.birth_fetal_death_certificate_parent.demographic_of_father.age,
         "birth_fetal_death_certificate_parent/demographic_of_father/education_level" => this.birth_fetal_death_certificate_parent.demographic_of_father.education_level,
         "birth_fetal_death_certificate_parent/demographic_of_father/is_father_of_hispanic_origin" => this.birth_fetal_death_certificate_parent.demographic_of_father.is_father_of_hispanic_origin,
         "birth_fetal_death_certificate_parent/demographic_of_mother/date_of_birth/month" => this.birth_fetal_death_certificate_parent.demographic_of_mother.date_of_birth.month,
         "birth_fetal_death_certificate_parent/demographic_of_mother/date_of_birth/day" => this.birth_fetal_death_certificate_parent.demographic_of_mother.date_of_birth.day,
         "birth_fetal_death_certificate_parent/demographic_of_mother/date_of_birth/year" => this.birth_fetal_death_certificate_parent.demographic_of_mother.date_of_birth.year,
         "birth_fetal_death_certificate_parent/demographic_of_mother/age" => this.birth_fetal_death_certificate_parent.demographic_of_mother.age,
         "birth_fetal_death_certificate_parent/demographic_of_mother/mother_married" => this.birth_fetal_death_certificate_parent.demographic_of_mother.mother_married,
         "birth_fetal_death_certificate_parent/demographic_of_mother/If_mother_not_married_has_paternity_acknowledgement_been_signed_in_the_hospital" => this.birth_fetal_death_certificate_parent.demographic_of_mother.If_mother_not_married_has_paternity_acknowledgement_been_signed_in_the_hospital,
         "birth_fetal_death_certificate_parent/demographic_of_mother/ever_in_us_armed_forces" => this.birth_fetal_death_certificate_parent.demographic_of_mother.ever_in_us_armed_forces,
         "birth_fetal_death_certificate_parent/demographic_of_mother/is_of_hispanic_origin" => this.birth_fetal_death_certificate_parent.demographic_of_mother.is_of_hispanic_origin,
         "birth_fetal_death_certificate_parent/demographic_of_mother/education_level" => this.birth_fetal_death_certificate_parent.demographic_of_mother.education_level,
         "birth_fetal_death_certificate_parent/location_of_residence/estimated_distance_from_residence" => this.birth_fetal_death_certificate_parent.location_of_residence.estimated_distance_from_residence,
         "birth_fetal_death_certificate_parent/pregnancy_history/date_of_last_live_birth/month" => this.birth_fetal_death_certificate_parent.pregnancy_history.date_of_last_live_birth.month,
         "birth_fetal_death_certificate_parent/pregnancy_history/date_of_last_live_birth/day" => this.birth_fetal_death_certificate_parent.pregnancy_history.date_of_last_live_birth.day,
         "birth_fetal_death_certificate_parent/pregnancy_history/date_of_last_live_birth/year" => this.birth_fetal_death_certificate_parent.pregnancy_history.date_of_last_live_birth.year,
         "birth_fetal_death_certificate_parent/pregnancy_history/live_birth_interval" => this.birth_fetal_death_certificate_parent.pregnancy_history.live_birth_interval,
         "birth_fetal_death_certificate_parent/pregnancy_history/number_of_previous_live_births" => this.birth_fetal_death_certificate_parent.pregnancy_history.number_of_previous_live_births,
         "birth_fetal_death_certificate_parent/pregnancy_history/now_living" => this.birth_fetal_death_certificate_parent.pregnancy_history.now_living,
         "birth_fetal_death_certificate_parent/pregnancy_history/now_dead" => this.birth_fetal_death_certificate_parent.pregnancy_history.now_dead,
         "birth_fetal_death_certificate_parent/pregnancy_history/other_outcomes" => this.birth_fetal_death_certificate_parent.pregnancy_history.other_outcomes,
         "birth_fetal_death_certificate_parent/pregnancy_history/date_of_last_other_outcome/month" => this.birth_fetal_death_certificate_parent.pregnancy_history.date_of_last_other_outcome.month,
         "birth_fetal_death_certificate_parent/pregnancy_history/date_of_last_other_outcome/day" => this.birth_fetal_death_certificate_parent.pregnancy_history.date_of_last_other_outcome.day,
         "birth_fetal_death_certificate_parent/pregnancy_history/date_of_last_other_outcome/year" => this.birth_fetal_death_certificate_parent.pregnancy_history.date_of_last_other_outcome.year,
         "birth_fetal_death_certificate_parent/maternal_biometrics/height_feet" => this.birth_fetal_death_certificate_parent.maternal_biometrics.height_feet,
         "birth_fetal_death_certificate_parent/maternal_biometrics/height_inches" => this.birth_fetal_death_certificate_parent.maternal_biometrics.height_inches,
         "birth_fetal_death_certificate_parent/maternal_biometrics/pre_pregnancy_weight" => this.birth_fetal_death_certificate_parent.maternal_biometrics.pre_pregnancy_weight,
         "birth_fetal_death_certificate_parent/maternal_biometrics/weight_at_delivery" => this.birth_fetal_death_certificate_parent.maternal_biometrics.weight_at_delivery,
         "birth_fetal_death_certificate_parent/maternal_biometrics/weight_gain" => this.birth_fetal_death_certificate_parent.maternal_biometrics.weight_gain,
         "birth_fetal_death_certificate_parent/maternal_biometrics/bmi" => this.birth_fetal_death_certificate_parent.maternal_biometrics.bmi,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_last_normal_menses/month" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_last_normal_menses.month,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_last_normal_menses/day" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_last_normal_menses.day,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_last_normal_menses/year" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_last_normal_menses.year,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_1st_prenatal_visit/month" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_1st_prenatal_visit.month,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_1st_prenatal_visit/day" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_1st_prenatal_visit.day,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_1st_prenatal_visit/year" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_1st_prenatal_visit.year,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_last_prenatal_visit/month" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_last_prenatal_visit.month,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_last_prenatal_visit/day" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_last_prenatal_visit.day,
         "birth_fetal_death_certificate_parent/prenatal_care/date_of_last_prenatal_visit/year" => this.birth_fetal_death_certificate_parent.prenatal_care.date_of_last_prenatal_visit.year,
         "birth_fetal_death_certificate_parent/prenatal_care/calculated_gestation" => this.birth_fetal_death_certificate_parent.prenatal_care.calculated_gestation,
         "birth_fetal_death_certificate_parent/prenatal_care/calculated_gestation_days" => this.birth_fetal_death_certificate_parent.prenatal_care.calculated_gestation_days,
         "birth_fetal_death_certificate_parent/prenatal_care/obsteric_estimate_of_gestation" => this.birth_fetal_death_certificate_parent.prenatal_care.obsteric_estimate_of_gestation,
         "birth_fetal_death_certificate_parent/prenatal_care/plurality" => this.birth_fetal_death_certificate_parent.prenatal_care.plurality,
         "birth_fetal_death_certificate_parent/prenatal_care/was_wic_used" => this.birth_fetal_death_certificate_parent.prenatal_care.was_wic_used,
         "birth_fetal_death_certificate_parent/prenatal_care/principal_source_of_payment_for_this_delivery" => this.birth_fetal_death_certificate_parent.prenatal_care.principal_source_of_payment_for_this_delivery,
         "birth_fetal_death_certificate_parent/prenatal_care/trimester_of_1st_prenatal_care_visit" => this.birth_fetal_death_certificate_parent.prenatal_care.trimester_of_1st_prenatal_care_visit,
         "birth_fetal_death_certificate_parent/prenatal_care/number_of_visits" => this.birth_fetal_death_certificate_parent.prenatal_care.number_of_visits,
         "birth_fetal_death_certificate_parent/cigarette_smoking/prior_3_months" => this.birth_fetal_death_certificate_parent.cigarette_smoking.prior_3_months,
         "birth_fetal_death_certificate_parent/cigarette_smoking/prior_3_months_type" => this.birth_fetal_death_certificate_parent.cigarette_smoking.prior_3_months_type,
         "birth_fetal_death_certificate_parent/cigarette_smoking/trimester_1st" => this.birth_fetal_death_certificate_parent.cigarette_smoking.trimester_1st,
         "birth_fetal_death_certificate_parent/cigarette_smoking/trimester_1st_type" => this.birth_fetal_death_certificate_parent.cigarette_smoking.trimester_1st_type,
         "birth_fetal_death_certificate_parent/cigarette_smoking/trimester_2nd" => this.birth_fetal_death_certificate_parent.cigarette_smoking.trimester_2nd,
         "birth_fetal_death_certificate_parent/cigarette_smoking/trimester_2nd_type" => this.birth_fetal_death_certificate_parent.cigarette_smoking.trimester_2nd_type,
         "birth_fetal_death_certificate_parent/cigarette_smoking/trimester_3rd" => this.birth_fetal_death_certificate_parent.cigarette_smoking.trimester_3rd,
         "birth_fetal_death_certificate_parent/cigarette_smoking/trimester_3rd_type" => this.birth_fetal_death_certificate_parent.cigarette_smoking.trimester_3rd_type,
         "birth_fetal_death_certificate_parent/cigarette_smoking/none_or_not_specified" => this.birth_fetal_death_certificate_parent.cigarette_smoking.none_or_not_specified,
         "birth_fetal_death_certificate_parent/risk_factors/number_of_c_sections" => this.birth_fetal_death_certificate_parent.risk_factors.number_of_c_sections,
         "birth_fetal_death_certificate_parent/length_between_child_birth_and_death_of_mother" => this.birth_fetal_death_certificate_parent.length_between_child_birth_and_death_of_mother,
         "cvs/cvs_used" => this.cvs.cvs_used,
         "cvs/cvs_used_how" => this.cvs.cvs_used_how,
         "social_and_environmental_profile/socio_economic_characteristics/source_of_income" => this.social_and_environmental_profile.socio_economic_characteristics.source_of_income,
         "social_and_environmental_profile/socio_economic_characteristics/employment_status" => this.social_and_environmental_profile.socio_economic_characteristics.employment_status,
         "social_and_environmental_profile/socio_economic_characteristics/immigration_status" => this.social_and_environmental_profile.socio_economic_characteristics.immigration_status,
         "social_and_environmental_profile/socio_economic_characteristics/time_in_the_us" => this.social_and_environmental_profile.socio_economic_characteristics.time_in_the_us,
         "social_and_environmental_profile/socio_economic_characteristics/time_in_the_us_units" => this.social_and_environmental_profile.socio_economic_characteristics.time_in_the_us_units,
         "social_and_environmental_profile/socio_economic_characteristics/current_living_arrangements" => this.social_and_environmental_profile.socio_economic_characteristics.current_living_arrangements,
         "social_and_environmental_profile/gender_identity/sep_genid_is_nonfemale" => this.social_and_environmental_profile.gender_identity.sep_genid_is_nonfemale,
         "social_and_environmental_profile/health_care_system/no_prenatal_care" => this.social_and_environmental_profile.health_care_system.no_prenatal_care,
         "social_and_environmental_profile/had_military_service" => this.social_and_environmental_profile.had_military_service,
         "social_and_environmental_profile/was_there_bereavement_support" => this.social_and_environmental_profile.was_there_bereavement_support,
         "social_and_environmental_profile/documented_substance_use" => this.social_and_environmental_profile.documented_substance_use,
         "autopsy_report/was_there_an_autopsy_referral" => this.autopsy_report.was_there_an_autopsy_referral,
         "autopsy_report/type_of_autopsy_or_examination" => this.autopsy_report.type_of_autopsy_or_examination,
         "autopsy_report/is_autopsy_or_exam_report_available" => this.autopsy_report.is_autopsy_or_exam_report_available,
         "autopsy_report/was_toxicology_performed" => this.autopsy_report.was_toxicology_performed,
         "autopsy_report/is_toxicology_report_available" => this.autopsy_report.is_toxicology_report_available,
         "autopsy_report/completeness_of_autopsy_information" => this.autopsy_report.completeness_of_autopsy_information,
         "autopsy_report/reporter_characteristics/reporter_type" => this.autopsy_report.reporter_characteristics.reporter_type,
         "autopsy_report/reporter_characteristics/date_of_autopsy/month" => this.autopsy_report.reporter_characteristics.date_of_autopsy.month,
         "autopsy_report/reporter_characteristics/date_of_autopsy/day" => this.autopsy_report.reporter_characteristics.date_of_autopsy.day,
         "autopsy_report/reporter_characteristics/date_of_autopsy/year" => this.autopsy_report.reporter_characteristics.date_of_autopsy.year,
         "autopsy_report/biometrics/mother/height/feet" => this.autopsy_report.biometrics.mother.height.feet,
         "autopsy_report/biometrics/mother/height/inches" => this.autopsy_report.biometrics.mother.height.inches,
         "autopsy_report/biometrics/mother/weight" => this.autopsy_report.biometrics.mother.weight,
         "autopsy_report/biometrics/mother/bmi" => this.autopsy_report.biometrics.mother.bmi,
         "autopsy_report/biometrics/fetus/fetal_weight_uom" => this.autopsy_report.biometrics.fetus.fetal_weight_uom,
         "autopsy_report/biometrics/fetus/fetal_weight" => this.autopsy_report.biometrics.fetus.fetal_weight,
         "autopsy_report/biometrics/fetus/fetal_weight_ounce_value" => this.autopsy_report.biometrics.fetus.fetal_weight_ounce_value,
         "autopsy_report/biometrics/fetus/fetal_length_uom" => this.autopsy_report.biometrics.fetus.fetal_length_uom,
         "autopsy_report/biometrics/fetus/fetal_length" => this.autopsy_report.biometrics.fetus.fetal_length,
         "autopsy_report/biometrics/fetus/gestational_age_estimate" => this.autopsy_report.biometrics.fetus.gestational_age_estimate,
         "autopsy_report/was_drug_toxicology_positive" => this.autopsy_report.was_drug_toxicology_positive,
         "prenatal/number_of_pnc_sources" => this.prenatal.number_of_pnc_sources,
         "prenatal/primary_prenatal_care_facility/place_type" => this.prenatal.primary_prenatal_care_facility.place_type,
         "prenatal/primary_prenatal_care_facility/primary_provider_type" => this.prenatal.primary_prenatal_care_facility.primary_provider_type,
         "prenatal/primary_prenatal_care_facility/principal_source_of_payment" => this.prenatal.primary_prenatal_care_facility.principal_source_of_payment,
         "prenatal/primary_prenatal_care_facility/is_use_wic" => this.prenatal.primary_prenatal_care_facility.is_use_wic,
         "prenatal/had_pre_existing_conditions" => this.prenatal.had_pre_existing_conditions,
         "prenatal/were_there_documented_mental_health_conditions" => this.prenatal.were_there_documented_mental_health_conditions,
         "prenatal/evidence_of_substance_use" => this.prenatal.evidence_of_substance_use,
         "prenatal/pregnancy_history/gravida" => this.prenatal.pregnancy_history.gravida,
         "prenatal/pregnancy_history/para" => this.prenatal.pregnancy_history.para,
         "prenatal/pregnancy_history/abortions" => this.prenatal.pregnancy_history.abortions,
         "prenatal/intendedenes/date_birth_control_was_discontinued/month" => this.prenatal.intendedenes.date_birth_control_was_discontinued.month,
         "prenatal/intendedenes/date_birth_control_was_discontinued/day" => this.prenatal.intendedenes.date_birth_control_was_discontinued.day,
         "prenatal/intendedenes/date_birth_control_was_discontinued/year" => this.prenatal.intendedenes.date_birth_control_was_discontinued.year,
         "prenatal/intendedenes/was_pregnancy_planned" => this.prenatal.intendedenes.was_pregnancy_planned,
         "prenatal/intendedenes/was_patient_using_birth_control" => this.prenatal.intendedenes.was_patient_using_birth_control,
         "prenatal/infertility_treatment/was_pregnancy_result_of_infertility_treatment" => this.prenatal.infertility_treatment.was_pregnancy_result_of_infertility_treatment,
         "prenatal/infertility_treatment/fertility_enhanding_drugs" => this.prenatal.infertility_treatment.fertility_enhanding_drugs,
         "prenatal/infertility_treatment/assisted_reproductive_technology" => this.prenatal.infertility_treatment.assisted_reproductive_technology,
         "prenatal/infertility_treatment/art_type" => this.prenatal.infertility_treatment.art_type,
         "prenatal/infertility_treatment/cycle_number" => this.prenatal.infertility_treatment.cycle_number,
         "prenatal/infertility_treatment/embryos_transferred" => this.prenatal.infertility_treatment.embryos_transferred,
         "prenatal/infertility_treatment/embryos_growing" => this.prenatal.infertility_treatment.embryos_growing,
         "prenatal/current_pregnancy/date_of_last_normal_menses/month" => this.prenatal.current_pregnancy.date_of_last_normal_menses.month,
         "prenatal/current_pregnancy/date_of_last_normal_menses/day" => this.prenatal.current_pregnancy.date_of_last_normal_menses.day,
         "prenatal/current_pregnancy/date_of_last_normal_menses/year" => this.prenatal.current_pregnancy.date_of_last_normal_menses.year,
         "prenatal/current_pregnancy/estimated_date_of_confinement/month" => this.prenatal.current_pregnancy.estimated_date_of_confinement.month,
         "prenatal/current_pregnancy/estimated_date_of_confinement/day" => this.prenatal.current_pregnancy.estimated_date_of_confinement.day,
         "prenatal/current_pregnancy/estimated_date_of_confinement/year" => this.prenatal.current_pregnancy.estimated_date_of_confinement.year,
         "prenatal/current_pregnancy/estimated_date_of_confinement/estimate_based_on" => this.prenatal.current_pregnancy.estimated_date_of_confinement.estimate_based_on,
         "prenatal/current_pregnancy/date_of_1st_prenatal_visit/month" => this.prenatal.current_pregnancy.date_of_1st_prenatal_visit.month,
         "prenatal/current_pregnancy/date_of_1st_prenatal_visit/day" => this.prenatal.current_pregnancy.date_of_1st_prenatal_visit.day,
         "prenatal/current_pregnancy/date_of_1st_prenatal_visit/year" => this.prenatal.current_pregnancy.date_of_1st_prenatal_visit.year,
         "prenatal/current_pregnancy/date_of_1st_prenatal_visit/gestational_age_weeks" => this.prenatal.current_pregnancy.date_of_1st_prenatal_visit.gestational_age_weeks,
         "prenatal/current_pregnancy/date_of_1st_prenatal_visit/gestational_age_days" => this.prenatal.current_pregnancy.date_of_1st_prenatal_visit.gestational_age_days,
         "prenatal/current_pregnancy/date_of_1st_ultrasound/month" => this.prenatal.current_pregnancy.date_of_1st_ultrasound.month,
         "prenatal/current_pregnancy/date_of_1st_ultrasound/day" => this.prenatal.current_pregnancy.date_of_1st_ultrasound.day,
         "prenatal/current_pregnancy/date_of_1st_ultrasound/year" => this.prenatal.current_pregnancy.date_of_1st_ultrasound.year,
         "prenatal/current_pregnancy/date_of_1st_ultrasound/gestational_age_at_first_ultrasound" => this.prenatal.current_pregnancy.date_of_1st_ultrasound.gestational_age_at_first_ultrasound,
         "prenatal/current_pregnancy/date_of_1st_ultrasound/gestational_age_at_first_ultrasound_days" => this.prenatal.current_pregnancy.date_of_1st_ultrasound.gestational_age_at_first_ultrasound_days,
         "prenatal/current_pregnancy/date_of_last_prenatal_visit/month" => this.prenatal.current_pregnancy.date_of_last_prenatal_visit.month,
         "prenatal/current_pregnancy/date_of_last_prenatal_visit/day" => this.prenatal.current_pregnancy.date_of_last_prenatal_visit.day,
         "prenatal/current_pregnancy/date_of_last_prenatal_visit/year" => this.prenatal.current_pregnancy.date_of_last_prenatal_visit.year,
         "prenatal/current_pregnancy/date_of_last_prenatal_visit/gestational_age_at_last_prenatal_visit" => this.prenatal.current_pregnancy.date_of_last_prenatal_visit.gestational_age_at_last_prenatal_visit,
         "prenatal/current_pregnancy/date_of_last_prenatal_visit/gestational_age_at_last_prenatal_visit_days" => this.prenatal.current_pregnancy.date_of_last_prenatal_visit.gestational_age_at_last_prenatal_visit_days,
         "prenatal/current_pregnancy/height/feet" => this.prenatal.current_pregnancy.height.feet,
         "prenatal/current_pregnancy/height/inches" => this.prenatal.current_pregnancy.height.inches,
         "prenatal/current_pregnancy/pre_pregnancy_weight" => this.prenatal.current_pregnancy.pre_pregnancy_weight,
         "prenatal/current_pregnancy/bmi" => this.prenatal.current_pregnancy.bmi,
         "prenatal/current_pregnancy/weight_at_1st_visit" => this.prenatal.current_pregnancy.weight_at_1st_visit,
         "prenatal/current_pregnancy/weight_at_last_visit" => this.prenatal.current_pregnancy.weight_at_last_visit,
         "prenatal/current_pregnancy/weight_gain" => this.prenatal.current_pregnancy.weight_gain,
         "prenatal/current_pregnancy/total_number_of_visits" => this.prenatal.current_pregnancy.total_number_of_visits,
         "prenatal/current_pregnancy/trimester_of_first_pnc_visit" => this.prenatal.current_pregnancy.trimester_of_first_pnc_visit,
         "prenatal/current_pregnancy/number_of_fetuses" => this.prenatal.current_pregnancy.number_of_fetuses,
         "prenatal/current_pregnancy/was_home_delivery_planned" => this.prenatal.current_pregnancy.was_home_delivery_planned,
         "prenatal/current_pregnancy/attended_prenatal_visits_alone" => this.prenatal.current_pregnancy.attended_prenatal_visits_alone,
         "prenatal/highest_blood_pressure/systolic" => this.prenatal.highest_blood_pressure.systolic,
         "prenatal/highest_blood_pressure/diastolic" => this.prenatal.highest_blood_pressure.diastolic,
         "prenatal/lowest_hematocrit" => this.prenatal.lowest_hematocrit,
         "prenatal/were_there_problems_identified" => this.prenatal.were_there_problems_identified,
         "prenatal/were_there_adverse_reactions" => this.prenatal.were_there_adverse_reactions,
         "prenatal/were_there_pre_delivery_hospitalizations" => this.prenatal.were_there_pre_delivery_hospitalizations,
         "prenatal/were_medical_referrals_to_others" => this.prenatal.were_medical_referrals_to_others,
         "mental_health_profile/were_there_documented_preexisting_mental_health_conditions" => this.mental_health_profile.were_there_documented_preexisting_mental_health_conditions,
         "committee_review/pregnancy_relatedness" => this.committee_review.pregnancy_relatedness,
         "committee_review/estimate_degree_relevant_information_available" => this.committee_review.estimate_degree_relevant_information_available,
         "committee_review/does_committee_agree_with_cod_on_death_certificate" => this.committee_review.does_committee_agree_with_cod_on_death_certificate,
         "committee_review/did_obesity_contribute_to_the_death" => this.committee_review.did_obesity_contribute_to_the_death,
         "committee_review/did_discrimination_contribute_to_the_death" => this.committee_review.did_discrimination_contribute_to_the_death,
         "committee_review/did_mental_health_conditions_contribute_to_the_death" => this.committee_review.did_mental_health_conditions_contribute_to_the_death,
         "committee_review/did_substance_use_disorder_contribute_to_the_death" => this.committee_review.did_substance_use_disorder_contribute_to_the_death,
         "committee_review/was_this_death_a_sucide" => this.committee_review.was_this_death_a_sucide,
         "committee_review/was_this_death_a_homicide" => this.committee_review.was_this_death_a_homicide,
         "committee_review/means_of_fatal_injury" => this.committee_review.means_of_fatal_injury,
         "committee_review/if_homicide_relationship_of_perpetrator" => this.committee_review.if_homicide_relationship_of_perpetrator,
         "committee_review/was_this_death_preventable" => this.committee_review.was_this_death_preventable,
         "committee_review/chance_to_alter_outcome" => this.committee_review.chance_to_alter_outcome,

            _ => null
        };
        
        return result;
    }

    public bool? GetSS_Boolean(string path)
    {
        bool? result = path.ToLower() switch
        {
//{get_boolean}
            _ => null
        };
        
        return result;
    }

    public List<double>? GetSS_List_Of_Double(string path)
    {
        List<double>? result = path.ToLower() switch
        {
         "home_record/how_was_this_death_identified" => this.home_record.how_was_this_death_identified,
         "death_certificate/race/race" => this.death_certificate.race.race,
         "birth_fetal_death_certificate_parent/demographic_of_father/race/race_of_father" => this.birth_fetal_death_certificate_parent.demographic_of_father.race.race_of_father,
         "birth_fetal_death_certificate_parent/race/race_of_mother" => this.birth_fetal_death_certificate_parent.race.race_of_mother,
         "birth_fetal_death_certificate_parent/risk_factors/risk_factors_in_this_pregnancy" => this.birth_fetal_death_certificate_parent.risk_factors.risk_factors_in_this_pregnancy,
         "birth_fetal_death_certificate_parent/infections_present_or_treated_during_pregnancy" => this.birth_fetal_death_certificate_parent.infections_present_or_treated_during_pregnancy,
         "birth_fetal_death_certificate_parent/onset_of_labor" => this.birth_fetal_death_certificate_parent.onset_of_labor,
         "birth_fetal_death_certificate_parent/obstetric_procedures" => this.birth_fetal_death_certificate_parent.obstetric_procedures,
         "birth_fetal_death_certificate_parent/characteristics_of_labor_and_delivery" => this.birth_fetal_death_certificate_parent.characteristics_of_labor_and_delivery,
         "birth_fetal_death_certificate_parent/maternal_morbidity" => this.birth_fetal_death_certificate_parent.maternal_morbidity,
         "social_and_environmental_profile/socio_economic_characteristics/homelessness" => this.social_and_environmental_profile.socio_economic_characteristics.homelessness,
         "social_and_environmental_profile/socio_economic_characteristics/unstable_housing" => this.social_and_environmental_profile.socio_economic_characteristics.unstable_housing,
         "social_and_environmental_profile/gender_identity/sep_genid_source" => this.social_and_environmental_profile.gender_identity.sep_genid_source,
         "social_and_environmental_profile/previous_or_current_incarcerations" => this.social_and_environmental_profile.previous_or_current_incarcerations,
         "social_and_environmental_profile/was_decedent_ever_arrested" => this.social_and_environmental_profile.was_decedent_ever_arrested,
         "social_and_environmental_profile/health_care_access/barriers_to_health_care_access" => this.social_and_environmental_profile.health_care_access.barriers_to_health_care_access,
         "social_and_environmental_profile/communications/barriers_to_communications" => this.social_and_environmental_profile.communications.barriers_to_communications,
         "social_and_environmental_profile/social_or_emotional_stress/evidence_of_social_or_emotional_stress" => this.social_and_environmental_profile.social_or_emotional_stress.evidence_of_social_or_emotional_stress,
         "social_and_environmental_profile/health_care_system/reasons_for_missed_appointments" => this.social_and_environmental_profile.health_care_system.reasons_for_missed_appointments,
         "mental_health_profile/mental_health_conditions_prior_to_the_most_recent_pregnancy" => this.mental_health_profile.mental_health_conditions_prior_to_the_most_recent_pregnancy,
         "mental_health_profile/mental_health_conditions_during_the_most_recent_pregnancy" => this.mental_health_profile.mental_health_conditions_during_the_most_recent_pregnancy,
         "mental_health_profile/mental_health_conditions_after_the_most_recent_pregnancy" => this.mental_health_profile.mental_health_conditions_after_the_most_recent_pregnancy,

            _ => null
        };
        
        return result;
    }

    
    public List<string>? GetSS_List_Of_String(string path)
    {
        List<string>? result = path.ToLower() switch
        {

            _ => null
        };
        
        return result;
    }

    public DateTime? GetSS_Datetime(string path)
    {
        DateTime? result = path.ToLower() switch
        {
         "date_created" => this.date_created,
         "date_last_updated" => this.date_last_updated,
         "date_last_checked_out" => this.date_last_checked_out,

            _ => null
        };
        
        return result;
    }


    public DateOnly? GetSS_Date_Only(string path)
    {
        DateOnly? result = path.ToLower() switch
        {
         "home_record/case_status/abstraction_begin_date" => this.home_record.case_status.abstraction_begin_date,
         "home_record/case_status/abstraction_complete_date" => this.home_record.case_status.abstraction_complete_date,
         "home_record/case_status/projected_review_date" => this.home_record.case_status.projected_review_date,
         "home_record/case_status/committee_review_date" => this.home_record.case_status.committee_review_date,
         "home_record/case_status/case_locked_date" => this.home_record.case_status.case_locked_date,
         "committee_review/date_of_review" => this.committee_review.date_of_review,

            _ => null
        };
        
        return result;
    }


    public TimeOnly? GetSS_Time_Only(string path)
    {
        TimeOnly? result = path.ToLower() switch
        {
         "death_certificate/certificate_identification/time_of_death" => this.death_certificate.certificate_identification.time_of_death,
         "death_certificate/injury_associated_information/time_of_injury" => this.death_certificate.injury_associated_information.time_of_injury,

            _ => null
        };
        
        return result;
    }


}