using System;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace mmria_pmss_client.Models.IJE;
public sealed class PMSS_Other_Specification
{
    public const int Size = 5000; 
    public string this[string i]
    {
        get { return data[i]; }
    }
    ImmutableDictionary<string, string> data = ImmutableDictionary.CreateRange
    (
        new KeyValuePair<string,string>[] 
        {

KeyValuePair.Create("batch_name","app/tracking/admin_info/batch_name"),
KeyValuePair.Create("fileno_dc","app/tracking/admin_info/fileno_dc"),
KeyValuePair.Create("fileno_bc","app/tracking/admin_info/fileno_bc"),
KeyValuePair.Create("fileno_fdc","	app/tracking/admin_info/fileno_fdc"),
KeyValuePair.Create("year_birthorfetaldeath	app/tracking/admin_info/year_birthorfetaldeath",""),
KeyValuePair.Create("pregcb_match	app/vro_case_determnation/cdc_case_matching_results/pregcb_match",""),
KeyValuePair.Create("literalcod_match	app/vro_case_determnation/cdc_case_matching_results/literalcod_match",""),
KeyValuePair.Create("icd10_match	app/vro_case_determnation/cdc_case_matching_results/icd10_match",""),
KeyValuePair.Create("bc_det_match	app/vro_case_determnation/cdc_case_matching_results/bc_det_match",""),
KeyValuePair.Create("fdc_det_match	app/vro_case_determnation/cdc_case_matching_results/fdc_det_match",""),
KeyValuePair.Create("bc_prob_match	app/vro_case_determnation/cdc_case_matching_results/bc_prob_match",""),
KeyValuePair.Create("fdc_prob_match	app/vro_case_determnation/cdc_case_matching_results/fdc_prob_match",""),
KeyValuePair.Create("vro_resolution_status	app/vro_case_determnation/vro_update/vro_resolution_status",""),
KeyValuePair.Create("vro_resolution_remarks	app/vro_case_determnation/vro_update/vro_resolution_remarks",""),
KeyValuePair.Create("Year	app/tracking/admin_info/track_year",""),
KeyValuePair.Create("CaseNo	app/tracking/admin_info/pmssno",""),
KeyValuePair.Create("PMSS_State_Code	app/tracking/admin_info/jurisdiction",""),
KeyValuePair.Create("Jurisdiction	NOT MAPPED",""),
KeyValuePair.Create("Jurisdiction_Name	NOT MAPPED",""),
KeyValuePair.Create("Status	app/tracking/admin_info/status",""),
KeyValuePair.Create("AmssNo	app/tracking/q1/amssno",""),
KeyValuePair.Create("AmssRel	app/tracking/q1/amssrel",""),
KeyValuePair.Create("Dc	app/tracking/death_certificate_number",""),
KeyValuePair.Create("Dod	app/tracking/date_of_death/dod",""),
KeyValuePair.Create("SourcNot	app/tracking/sourcnot",""),
KeyValuePair.Create("DcFile	app/tracking/dcfile",""),
KeyValuePair.Create("LbFile	app/tracking/lbfile",""),
KeyValuePair.Create("PregStat	app/tracking/q7/pregstat",""),
KeyValuePair.Create("PcbTime	app/tracking/q7/pcbtime",""),
KeyValuePair.Create("StatDth	app/tracking/statdth",""),
KeyValuePair.Create("StatRes	app/tracking/q9/statres",""),
KeyValuePair.Create("ResZip	app/tracking/q9/reszip",""),
KeyValuePair.Create("ZipSrce	app/tracking/q9/zipsrce",""),
KeyValuePair.Create("County	app/tracking/q9/county",""),
KeyValuePair.Create("CntySrce	app/tracking/q9/cntysrce",""),
KeyValuePair.Create("MAge	app/demographic/mage",""),
KeyValuePair.Create("Dob	app/tracking/date_of_death/dob",""),
KeyValuePair.Create("AgeDif	app/tracking/date_of_death/agedif",""),
KeyValuePair.Create("Race	app/demographic/q12/race",""),
KeyValuePair.Create("Race_Oth	app/demographic/q12/group/race_oth",""),
KeyValuePair.Create("Race_Source	app/demographic/q12/group/race_source",""),
KeyValuePair.Create("Race_OMB	app/demographic/q12/group/race_omb",""),
KeyValuePair.Create("Race_White	app/demographic/q12/group/race_white",""),
KeyValuePair.Create("Race_Black	app/demographic/q12/group/race_black",""),
KeyValuePair.Create("Race_AmIndAlkNat	app/demographic/q12/group/race_amindalknat",""),
KeyValuePair.Create("Race_AsianIndian	app/demographic/q12/group/race_asianindian",""),
KeyValuePair.Create("Race_Chinese	app/demographic/q12/group/race_chinese",""),
KeyValuePair.Create("Race_Filipino	app/demographic/q12/group/race_filipino",""),
KeyValuePair.Create("Race_Japanese	app/demographic/q12/group/race_japanese",""),
KeyValuePair.Create("Race_Korean	app/demographic/q12/group/race_korean",""),
KeyValuePair.Create("Race_Vietnamese	app/demographic/q12/group/race_vietnamese",""),
KeyValuePair.Create("Race_OtherAsian	app/demographic/q12/group/race_otherasian",""),
KeyValuePair.Create("Race_NativeHawaiian	app/demographic/q12/group/race_nativehawaiian",""),
KeyValuePair.Create("Race_GuamCham	app/demographic/q12/group/race_guamcham",""),
KeyValuePair.Create("Race_Samoan	app/demographic/q12/group/race_samoan",""),
KeyValuePair.Create("Race_OtherPacific	app/demographic/q12/group/race_otherpacific",""),
KeyValuePair.Create("Race_Other	app/demographic/q12/group/race_other",""),
KeyValuePair.Create("Race_NotSpecified	app/demographic/q12/group/race_notspecified",""),
KeyValuePair.Create("HispOrg	app/demographic/q12/ethnicity/hisporg",""),
KeyValuePair.Create("Hisp_Oth	app/demographic/q12/ethnicity/hisp_oth",""),
KeyValuePair.Create("MatBplc	app/demographic/q12/matbplc",""),
KeyValuePair.Create("MatBplc_US	app/demographic/q12/matbplc_us",""),
KeyValuePair.Create("MatBplc_Else	app/demographic/q12/matbplc_else",""),
KeyValuePair.Create("MarStat	app/demographic/marstat",""),
KeyValuePair.Create("EducaTn	app/demographic/q14/educatn",""),
KeyValuePair.Create("PlaceDth	app/demographic/placedth",""),
KeyValuePair.Create("Pnc	app/demographic/pnc",""),
KeyValuePair.Create("Autopsy3	app/demographic/autopsy3",""),
KeyValuePair.Create("Height	app/demographic/height",""),
KeyValuePair.Create("WtPrePrg	app/demographic/wtpreprg",""),
KeyValuePair.Create("PrevLb	app/demographic/prevlb",""),
KeyValuePair.Create("PrvOthPg	app/demographic/prvothpg",""),
KeyValuePair.Create("PymtSrc	app/demographic/pymtsrc",""),
KeyValuePair.Create("Wic	app/demographic/wic",""),
KeyValuePair.Create("OutIndx	app/outcome/outindx",""),
KeyValuePair.Create("MultGest	app/outcome/multgest",""),
KeyValuePair.Create("TermProc	app/outcome/q25/termproc",""),
KeyValuePair.Create("TermPro1	app/outcome/q25/termpro1",""),
KeyValuePair.Create("TermPro2	app/outcome/q25/termpro2",""),
KeyValuePair.Create("GestWk	app/outcome/gestwk",""),
KeyValuePair.Create("DTerm	app/outcome/dterm_grp/dterm",""),
KeyValuePair.Create("DayDif	app/outcome/dterm_grp/daydif",""),
KeyValuePair.Create("CdcCod	app/cause_of_death/q28/cdccod",""),
KeyValuePair.Create("Cod	app/cause_of_death/q28/cod",""),
KeyValuePair.Create("AssoC1	app/cause_of_death/q29/assoc1",""),
KeyValuePair.Create("Acon1	app/cause_of_death/q29/acon1",""),
KeyValuePair.Create("AssoC2	app/cause_of_death/q30/assoc2",""),
KeyValuePair.Create("Acon2	app/cause_of_death/q30/acon2",""),
KeyValuePair.Create("AssoC3	app/cause_of_death/q31/assoc3",""),
KeyValuePair.Create("Acon3	app/cause_of_death/q31/acon3",""),
KeyValuePair.Create("Injury	app/cause_of_death/injury",""),
KeyValuePair.Create("Drug_1	app/cause_of_death/q33/drug_1",""),
KeyValuePair.Create("Drug_2	app/cause_of_death/q33/drug_2",""),
KeyValuePair.Create("Drug_3	app/cause_of_death/q33/drug_3",""),
KeyValuePair.Create("Class	app/cause_of_death/class",""),
KeyValuePair.Create("Coder	app/cause_of_death/coder",""),
KeyValuePair.Create("ClsMo	app/cause_of_death/clsmo",""),
KeyValuePair.Create("ClsYr	app/cause_of_death/clsyr",""),
KeyValuePair.Create("Tribe	app/demographic/q12/group/tribe",""),
KeyValuePair.Create("Occup	app/demographic/q14/occup",""),
KeyValuePair.Create("Indust	app/demographic/q14/indust",""),
KeyValuePair.Create("Bmi	app/demographic/bmi",""),
KeyValuePair.Create("Ethnic_Mexican	app/demographic/q12/ethnicity/ethnic1_mex",""),
KeyValuePair.Create("Ethnic_PR	app/demographic/q12/ethnicity/ethnic2_pr",""),
KeyValuePair.Create("Ethnic_Cuban	app/demographic/q12/ethnicity/ethnic3_cub",""),
KeyValuePair.Create("Ethnic_Other	app/demographic/q12/ethnicity/ethnic4_other",""),
KeyValuePair.Create("Drug_IV	app/cause_of_death/q33/drug_iv",""),
KeyValuePair.Create("Dod_MO	app/tracking/date_of_death/month",""),
KeyValuePair.Create("Dod_DY	app/tracking/date_of_death/day",""),
KeyValuePair.Create("Dod_YR	app/tracking/date_of_death/year",""),
KeyValuePair.Create("Dod_TM	app/tracking/date_of_death/time_of_death",""),
KeyValuePair.Create("Dob_MO	app/tracking/date_of_birth/month",""),
KeyValuePair.Create("Dob_DY	app/tracking/date_of_birth /day",""),
KeyValuePair.Create("Dob_YR	app/tracking/date_of_birth /year",""),
KeyValuePair.Create("DTerm_MO	app/outcome/dterm_grp/dterm/dterm_mo",""),
KeyValuePair.Create("DTerm_DY	app/outcome/dterm_grp/dterm/dterm_dy",""),
KeyValuePair.Create("DTerm_YR	app/outcome/dterm_grp/dterm/dterm_yr",""),
KeyValuePair.Create("DTerm_TM	app/outcome/dterm_grp/dterm/dterm_tm",""),
KeyValuePair.Create("Review_1_By	app/preparer_remarks/preparer_grp/review_1_by",""),
KeyValuePair.Create("Review_1_On	app/preparer_remarks/preparer_grp/review_1_on",""),
KeyValuePair.Create("Review_1_Remarks	app/preparer_remarks/preparer_grp/review_1_remarks",""),
KeyValuePair.Create("Remarks	app/preparer_remarks/remarks_grp/remarks",""),
KeyValuePair.Create("Update_Remarks	app/preparer_remarks/remarks_grp/update_remarks",""),
KeyValuePair.Create("Pdf_Link	app/preparer_remarks/pdf_grp/pdf_link",""),
KeyValuePair.Create("Pdf_Steve_Link	app/preparer_remarks/pdf_grp/pdf_steve_link",""),
KeyValuePair.Create("Review_2_By	app/committee_review/reviewer_grp/review_2_by",""),
KeyValuePair.Create("Review_2_On	app/committee_review/reviewer_grp/review_2_on",""),
KeyValuePair.Create("Review_2_Remarks	app/committee_review/reviewer_grp/review_2_remarks",""),
KeyValuePair.Create("dc_info_complete	app/committee_review/rev_assessment_grp/dc_info_complete",""),
KeyValuePair.Create("dc_info_remarks	app/committee_review/rev_assessment_grp/dc_info_remarks",""),
KeyValuePair.Create("mmria_used	app/committee_review/rev_assessment_grp/mmria_used",""),
KeyValuePair.Create("mmria_used_remarks	app/committee_review/rev_assessment_grp/mmria_used_remarks",""),
KeyValuePair.Create("agreement_status	app/committee_review/agreement_grp/agreement_status",""),
KeyValuePair.Create("agreement_remarks	app/committee_review/agreement_grp/agreement_remarks",""),
KeyValuePair.Create("transprt_dc	app/ije_dc/death_info/transprt_dc",""),
KeyValuePair.Create("manner_dc	app/ije_dc/cause_details/manner_dc",""),
KeyValuePair.Create("cod1a_dc	app/ije_dc/cause_details/cod1a_dc",""),
KeyValuePair.Create("interval1a_dc	app/ije_dc/cause_details/interval1a_dc",""),
KeyValuePair.Create("cod1b_dc	app/ije_dc/cause_details/cod1b_dc",""),
KeyValuePair.Create("interval1b_dc	app/ije_dc/cause_details/interval1b_dc",""),
KeyValuePair.Create("cod1c_dc	app/ije_dc/cause_details/cod1c_dc",""),
KeyValuePair.Create("interval1c_dc	app/ije_dc/cause_details/interval1c_dc",""),
KeyValuePair.Create("cod1d_dc	app/ije_dc/cause_details/cod1d_dc",""),
KeyValuePair.Create("interval1d_dc	app/ije_dc/cause_details/interval1d_dc",""),
KeyValuePair.Create("othercondition_dc	app/ije_dc/cause_details/othercondition_dc",""),
KeyValuePair.Create("man_uc_dc	app/ije_dc/cause_details/man_uc_dc",""),
KeyValuePair.Create("acme_uc_dc	app/ije_dc/cause_details/acme_uc_dc",""),
KeyValuePair.Create("eac_dc	app/ije_dc/cause_details/eac_dc",""),
KeyValuePair.Create("rac_dc	app/ije_dc/cause_details/rac_dc",""),
KeyValuePair.Create("howinj_dc	app/ije_dc/injury_details/howinj_dc","")




    });




}