using System;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace mmria_pmss_client.Models.IJE;
public sealed class PMSS_All
{
    public PMSS_All() {}

    public string batch_name{ get; set; }
    public string fileno_dc{ get; set; }
    public string fileno_bc{ get; set; }
    public string fileno_fdc{ get; set; }
    public string year_birthorfetaldeath{ get; set; }
    public string pregcb_match{ get; set; }
    public string literalcod_match{ get; set; }
    public string icd10_match{ get; set; }
    public string bc_det_match{ get; set; }
    public string fdc_det_match{ get; set; }
    public string bc_prob_match{ get; set; }
    public string fdc_prob_match{ get; set; }
    public string vro_resolution_status{ get; set; }
    public string vro_resolution_remarks{ get; set; }
    public string Year{ get; set; }
    public string CaseNo{ get; set; }
    public string PMSS_State_Code{ get; set; }
    //public string Jurisdiction	NOT MAPPED"),
    //public string Jurisdiction_Name	NOT MAPPED"),
    public string Status{ get; set; }
    public string AmssNo{ get; set; }
    public string AmssRel{ get; set; }
    public string Dc{ get; set; }
    public string Dod{ get; set; }
    public string SourcNot{ get; set; }
    public string DcFile{ get; set; }
    public string LbFile{ get; set; }
    public string PregStat{ get; set; }
    public string PcbTime{ get; set; }
    public string StatDth{ get; set; }
    public string StatRes{ get; set; }
    public string ResZip{ get; set; }
    public string ZipSrce{ get; set; }
    public string County{ get; set; }
    public string CntySrce{ get; set; }
    public string MAge{ get; set; }
    public string Dob{ get; set; }
    public string AgeDif{ get; set; }
    public string Race{ get; set; }
    public string Race_Oth{ get; set; }
    public string Race_Source{ get; set; }
    public string Race_OMB{ get; set; }
    public string Race_White{ get; set; }
    public string Race_Black{ get; set; }
    public string Race_AmIndAlkNat{ get; set; }
    public string Race_AsianIndian{ get; set; }
    public string Race_Chinese{ get; set; }
    public string Race_Filipino{ get; set; }
    public string Race_Japanese{ get; set; }
    public string Race_Korean{ get; set; }
    public string Race_Vietnamese{ get; set; }
    public string Race_OtherAsian{ get; set; }
    public string Race_NativeHawaiian{ get; set; }
    public string Race_GuamCham{ get; set; }
    public string Race_Samoan{ get; set; }
    public string Race_OtherPacific{ get; set; }
    public string Race_Other{ get; set; }
    public string Race_NotSpecified{ get; set; }
    public string HispOrg{ get; set; }
    public string Hisp_Oth{ get; set; }
    public string MatBplc{ get; set; }
    public string MatBplc_US{ get; set; }
    public string MatBplc_Else{ get; set; }
    public string MarStat{ get; set; }
    public string EducaTn{ get; set; }
    public string PlaceDth{ get; set; }
    public string Pnc{ get; set; }
    public string Autopsy3{ get; set; }
    public string Height{ get; set; }
    public string WtPrePrg{ get; set; }
    public string PrevLb{ get; set; }
    public string PrvOthPg{ get; set; }
    public string PymtSrc{ get; set; }
    public string Wic{ get; set; }
    public string OutIndx{ get; set; }
    public string MultGest{ get; set; }
    public string TermProc{ get; set; }
    public string TermPro1{ get; set; }
    public string TermPro2{ get; set; }
    public string GestWk{ get; set; }
    public string DTerm{ get; set; }
    public string DayDif{ get; set; }
    public string CdcCod{ get; set; }
    public string Cod{ get; set; }
    public string AssoC1{ get; set; }
    public string Acon1{ get; set; }
    public string AssoC2{ get; set; }
    public string Acon2{ get; set; }
    public string AssoC3{ get; set; }
    public string Acon3{ get; set; }
    public string Injury{ get; set; }
    public string Drug_1{ get; set; }
    public string Drug_2{ get; set; }
    public string Drug_3{ get; set; }
    public string Class{ get; set; }
    public string Coder{ get; set; }
    public string ClsMo{ get; set; }
    public string ClsYr{ get; set; }
    public string Tribe{ get; set; }
    public string Occup{ get; set; }
    public string Indust{ get; set; }
    public string Bmi{ get; set; }
    public string Ethnic_Mexican{ get; set; }
    public string Ethnic_PR{ get; set; }
    public string Ethnic_Cuban{ get; set; }
    public string Ethnic_Other{ get; set; }
    public string Drug_IV{ get; set; }
    public string Dod_MO{ get; set; }
    public string Dod_DY{ get; set; }
    public string Dod_YR{ get; set; }
    public string Dod_TM{ get; set; }
    public string Dob_MO{ get; set; }
    public string Dob_DY{ get; set; }
    public string Dob_YR{ get; set; }
    public string DTerm_MO{ get; set; }
    public string DTerm_DY{ get; set; }
    public string DTerm_YR{ get; set; }
    public string DTerm_TM{ get; set; }
    public string Review_1_By{ get; set; }
    public string Review_1_On{ get; set; }
    public string Review_1_Remarks{ get; set; }
    public string Remarks{ get; set; }
    public string Update_Remarks{ get; set; }
    public string Pdf_Link{ get; set; }
    public string Pdf_Steve_Link{ get; set; }
    public string Review_2_By{ get; set; }
    public string Review_2_On{ get; set; }
    public string Review_2_Remarks{ get; set; }
    public string dc_info_complete{ get; set; }
    public string dc_info_remarks{ get; set; }
    public string mmria_used{ get; set; }
    public string mmria_used_remarks{ get; set; }
    public string agreement_status{ get; set; }
    public string agreement_remarks{ get; set; }
    //public string fileno_dc{ get; set; }
    public string auxno_dc{ get; set; }
    public string replace_dc{ get; set; }
    public string void_dc{ get; set; }
    public string dod_mo_dc{ get; set; }
    public string dod_dy_dc{ get; set; }
    public string dod_yr_dc{ get; set; }
    public string tod_dc{ get; set; }
    public string dplace_dc{ get; set; }
    public string citytext_d_dc{ get; set; }
    public string countytext_d_dc{ get; set; }
    public string statetext_d_dc{ get; set; }
    public string zip9_d_dc{ get; set; }
    public string preg_dc{ get; set; }
    public string inact_dc{ get; set; }
    public string autop_dc{ get; set; }
    public string autopf_dc{ get; set; }
    public string transprt_dc{ get; set; }
    public string tobac_dc{ get; set; }
    public string manner_dc{ get; set; }
    public string cod1a_dc{ get; set; }
    public string interval1a_dc{ get; set; }
    public string cod1b_dc{ get; set; }
    public string interval1b_dc{ get; set; }
    public string cod1c_dc{ get; set; }
    public string interval1c_dc{ get; set; }
    public string cod1d_dc{ get; set; }
    public string interval1d_dc{ get; set; }
    public string othercondition_dc{ get; set; }
    public string man_uc_dc{ get; set; }
    public string acme_uc_dc{ get; set; }
    public string eac_dc{ get; set; }
    public string rac_dc{ get; set; }
    public string doi_mo_dc{ get; set; }
    public string doi_dy_dc{ get; set; }
    public string doi_yr_dc{ get; set; }
    public string toi_hr_dc{ get; set; }
    public string howinj_dc{ get; set; }
    public string workinj_dc{ get; set; }
    public string bplace_cnt_dc{ get; set; }
    public string bplace_st_dc{ get; set; }
    public string cityc_dc{ get; set; }
    public string citytext_r_dc{ get; set; }
    public string countyc_dc{ get; set; }
    public string countrytext_r_dc{ get; set; }
    public string statec_dc{ get; set; }
    public string statetext_r_dc{ get; set; }
    public string zip9_r_dc{ get; set; }
    public string dob_mo_dc{ get; set; }
    public string dob_dy_dc{ get; set; }
    public string dob_yr_dc{ get; set; }
    public string agetype_dc{ get; set; }
    public string age_dc{ get; set; }
    public string sex_dc{ get; set; }
    public string marital_dc{ get; set; }
    public string deduc_dc{ get; set; }
    public string indust_dc{ get; set; }
    public string occup_dc{ get; set; }
    public string armedf_dc{ get; set; }
    public string dethnic1_dc{ get; set; }
    public string dethnic2_dc{ get; set; }
    public string dethnic3_dc{ get; set; }
    public string dethnic4_dc{ get; set; }
    public string dethnic5_dc{ get; set; }
    public string race1_dc{ get; set; }
    public string race2_dc{ get; set; }
    public string race3_dc{ get; set; }
    public string race4_dc{ get; set; }
    public string race5_dc{ get; set; }
    public string race6_dc{ get; set; }
    public string race7_dc{ get; set; }
    public string race8_dc{ get; set; }
    public string race9_dc{ get; set; }
    public string race10_dc{ get; set; }
    public string race11_dc{ get; set; }
    public string race12_dc{ get; set; }
    public string race13_dc{ get; set; }
    public string race14_dc{ get; set; }
    public string race15_dc{ get; set; }
    public string race16_dc{ get; set; }
    public string race17_dc{ get; set; }
    public string race18_dc{ get; set; }
    public string race19_dc{ get; set; }
    public string race20_dc{ get; set; }
    public string race21_dc{ get; set; }
    public string race22_dc{ get; set; }
    public string race23_dc{ get; set; }
    public string bstate_bc{ get; set; }
    //public string fileno_bc{ get; set; }
    public string auxno_bc{ get; set; }
    public string void_bc{ get; set; }
    public string replace_bc{ get; set; }
    public string dwgt_bc{ get; set; }
    public string pwgt_bc{ get; set; }
    public string hft_bc{ get; set; }
    public string hin_bc{ get; set; }
    public string idob_mo_bc{ get; set; }
    public string idob_dy_bc{ get; set; }
    public string idob_yr_bc{ get; set; }
    public string tb_bc{ get; set; }
    public string isex_bc{ get; set; }
    public string bwg_bc{ get; set; }
    public string owgest_bc{ get; set; }
    public string apgar5_bc{ get; set; }
    public string apgar10_bc{ get; set; }
    public string plur_bc{ get; set; }
    public string sord_bc{ get; set; }
    public string hosp_bc{ get; set; }
    public string birth_co_bc{ get; set; }
    public string bplace_bc{ get; set; }
    public string attend_bc{ get; set; }
    public string tran_bc{ get; set; }
    public string itran_bc{ get; set; }
    public string bfed_bc{ get; set; }
    public string wic_bc{ get; set; }
    public string pay_bc{ get; set; }
    public string pres_bc{ get; set; }
    public string rout_bc{ get; set; }
    public string iliv_bc{ get; set; }
    public string gon_bc{ get; set; }
    public string syph_bc{ get; set; }
    public string hsv_bc{ get; set; }
    public string cham_bc{ get; set; }
    public string hepb_bc{ get; set; }
    public string hepc_bc{ get; set; }
    public string cerv_bc{ get; set; }
    public string toc_bc{ get; set; }
    public string ecvs_bc{ get; set; }
    public string ecvf_bc{ get; set; }
    public string prom_bc{ get; set; }
    public string pric_bc{ get; set; }
    public string prol_bc{ get; set; }
    public string indl_bc{ get; set; }
    public string augl_bc{ get; set; }
    public string nvpr_bc{ get; set; }
    public string ster_bc{ get; set; }
    public string antb_bc{ get; set; }
    public string chor_bc{ get; set; }
    public string mecs_bc{ get; set; }
    public string fint_bc{ get; set; }
    public string esan_bc{ get; set; }
    public string tlab_bc{ get; set; }
    public string mtr_bc{ get; set; }
    public string plac_bc{ get; set; }
    public string rut_bc{ get; set; }
    public string uhys_bc{ get; set; }
    public string aint_bc{ get; set; }
    public string uopr_bc{ get; set; }
    public string aven1_bc{ get; set; }
    public string aven6_bc{ get; set; }
    public string nicu_bc{ get; set; }
    public string surf_bc{ get; set; }
    public string anti_bc{ get; set; }
    public string seiz_bc{ get; set; }
    public string binj_bc{ get; set; }
    public string anen_bc{ get; set; }
    public string minsb_bc{ get; set; }
    public string cchd_bc{ get; set; }
    public string cdh_bc{ get; set; }
    public string omph_bc{ get; set; }
    public string gast_bc{ get; set; }
    public string limb_bc{ get; set; }
    public string cl_bc{ get; set; }
    public string cp_bc{ get; set; }
    public string dowt_bc{ get; set; }
    public string cdit_bc{ get; set; }
    public string hypo_bc{ get; set; }
    public string dlmp_mo_bc{ get; set; }
    public string dlmp_dy_bc{ get; set; }
    public string dlmp_yr_bc{ get; set; }
    public string dofp_mo_bc{ get; set; }
    public string dofp_dy_bc{ get; set; }
    public string dofp_yr_bc{ get; set; }
    public string dolp_mo_bc{ get; set; }
    public string dolp_dy_bc{ get; set; }
    public string dolp_yr_bc{ get; set; }
    public string nprev_bc{ get; set; }
    public string plbl_bc{ get; set; }
    public string plbd_bc{ get; set; }
    public string popo_bc{ get; set; }
    public string mllb_bc{ get; set; }
    public string yllb_bc{ get; set; }
    public string mopo_bc{ get; set; }
    public string yopo_bc{ get; set; }
    public string cigpn_bc{ get; set; }
    public string cigfn_bc{ get; set; }
    public string cigsn_bc{ get; set; }
    public string cigln_bc{ get; set; }
    public string pdiab_bc{ get; set; }
    public string gdiab_bc{ get; set; }
    public string phype_bc{ get; set; }
    public string ghype_bc{ get; set; }
    public string ppb_bc{ get; set; }
    public string ppo_bc{ get; set; }
    public string inft_bc{ get; set; }
    public string pces_bc{ get; set; }
    public string npces_bc{ get; set; }
    public string ehype_bc{ get; set; }
    public string inft_drg_bc{ get; set; }
    public string inft_art_bc{ get; set; }
    public string citytext_bc{ get; set; }
    public string countytxt_bc{ get; set; }
    public string statetxt_bc{ get; set; }
    public string zipcode_bc{ get; set; }
    public string mbplace_st_ter_tx_bc{ get; set; }
    public string mbplace_cntry_tx_bc{ get; set; }
    public string mager_bc{ get; set; }
    public string mdob_mo_bc{ get; set; }
    public string mdob_dy_bc{ get; set; }
    public string mdob_yr_bc{ get; set; }
    public string marn_bc{ get; set; }
    public string ackn_bc{ get; set; }
    public string meduc_bc{ get; set; }
    public string mom_in_t_bc{ get; set; }
    public string mom_oc_t_bc{ get; set; }
    public string methnic1_bc{ get; set; }
    public string methnic2_bc{ get; set; }
    public string methnic3_bc{ get; set; }
    public string methnic4_bc{ get; set; }
    public string methnic5_bc{ get; set; }
    public string mrace1_bc{ get; set; }
    public string mrace2_bc{ get; set; }
    public string mrace3_bc{ get; set; }
    public string mrace4_bc{ get; set; }
    public string mrace5_bc{ get; set; }
    public string mrace6_bc{ get; set; }
    public string mrace7_bc{ get; set; }
    public string mrace8_bc{ get; set; }
    public string mrace9_bc{ get; set; }
    public string mrace10_bc{ get; set; }
    public string mrace11_bc{ get; set; }
    public string mrace12_bc{ get; set; }
    public string mrace13_bc{ get; set; }
    public string mrace14_bc{ get; set; }
    public string mrace15_bc{ get; set; }
    public string mrace16_bc{ get; set; }
    public string mrace17_bc{ get; set; }
    public string mrace18_bc{ get; set; }
    public string mrace19_bc{ get; set; }
    public string mrace20_bc{ get; set; }
    public string mrace21_bc{ get; set; }
    public string mrace22_bc{ get; set; }
    public string mrace23_bc{ get; set; }
    public string fager_bc{ get; set; }
    public string dad_in_t_bc{ get; set; }
    public string dad_oc_t_bc{ get; set; }
    public string fbplacd_st_ter_c_bc{ get; set; }
    public string fbplace_cnt_c_bc{ get; set; }
    public string dstate_fdc{ get; set; }
    //public string fileno_fdc{ get; set; }
    public string auxno_fdc{ get; set; }
    public string void_fdc{ get; set; }
    public string replace_fdc{ get; set; }
    public string fdod_mo_fdc{ get; set; }
    public string fdod_dy_fdc{ get; set; }
    public string fdod_yr_fdc{ get; set; }
    public string td_fdc{ get; set; }
    public string dwgt_fdc{ get; set; }
    public string pwgt_fdc{ get; set; }
    public string hft_fdc{ get; set; }
    public string hin_fdc{ get; set; }
    public string fsex_fdc{ get; set; }
    public string fwg_fdc{ get; set; }
    public string owgest_fdc{ get; set; }
    public string plur_fdc{ get; set; }
    public string sord_fdc{ get; set; }
    public string hosp_d_fdc{ get; set; }
    public string cnty_d_fdc{ get; set; }
    public string city_d_fdc{ get; set; }
    public string attend_fdc{ get; set; }
    public string tran_fdc{ get; set; }
    public string wic_fdc{ get; set; }
    public string pres_fdc{ get; set; }
    public string rout_fdc{ get; set; }
    public string gon_fdc{ get; set; }
    public string syph_fdc{ get; set; }
    public string hsv_fdc{ get; set; }
    public string cham_fdc{ get; set; }
    public string lm_fdc{ get; set; }
    public string gbs_fdc{ get; set; }
    public string cmv_fdc{ get; set; }
    public string b19_fdc{ get; set; }
    public string toxo_fdc{ get; set; }
    public string hsv1_fdc{ get; set; }
    public string hiv_fdc{ get; set; }
    public string tlab_fdc{ get; set; }
    public string otheri_fdc{ get; set; }
    public string mtr_fdc{ get; set; }
    public string plac_fdc{ get; set; }
    public string rut_fdc{ get; set; }
    public string uhys_fdc{ get; set; }
    public string aint_fdc{ get; set; }
    public string uopr_fdc{ get; set; }
    public string anen_fdc{ get; set; }
    public string mnsb_fdc{ get; set; }
    public string cchd_fdc{ get; set; }
    public string cdh_fdc{ get; set; }
    public string omph_fdc{ get; set; }
    public string gast_fdc{ get; set; }
    public string limb_fdc{ get; set; }
    public string cl_fdc{ get; set; }
    public string caf_fdc{ get; set; }
    public string dowt_fdc{ get; set; }
    public string cdit_fdc{ get; set; }
    public string hypo_fdc{ get; set; }
    public string cod18a1_fdc{ get; set; }
    public string cod18a2_fdc{ get; set; }
    public string cod18a3_fdc{ get; set; }
    public string cod18a4_fdc{ get; set; }
    public string cod18a5_fdc{ get; set; }
    public string cod18a6_fdc{ get; set; }
    public string cod18a7_fdc{ get; set; }
    public string cod18a8_fdc{ get; set; }
    public string cod18a9_fdc{ get; set; }
    public string cod18a10_fdc{ get; set; }
    public string cod18a11_fdc{ get; set; }
    public string cod18a12_fdc{ get; set; }
    public string cod18a13_fdc{ get; set; }
    public string cod18a14_fdc{ get; set; }
    public string cod18b1_fdc{ get; set; }
    public string cod18b2_fdc{ get; set; }
    public string cod18b3_fdc{ get; set; }
    public string cod18b4_fdc{ get; set; }
    public string cod18b5_fdc{ get; set; }
    public string cod18b6_fdc{ get; set; }
    public string cod18b7_fdc{ get; set; }
    public string cod18b8_fdc{ get; set; }
    public string cod18b9_fdc{ get; set; }
    public string cod18b10_fdc{ get; set; }
    public string cod18b11_fdc{ get; set; }
    public string cod18b12_fdc{ get; set; }
    public string cod18b13_fdc{ get; set; }
    public string cod18b14_fdc{ get; set; }
    public string icod_fdc{ get; set; }
    public string ocod1_fdc{ get; set; }
    public string ocod2_fdc{ get; set; }
    public string ocod3_fdc{ get; set; }
    public string ocod4_fdc{ get; set; }
    public string ocod5_fdc{ get; set; }
    public string ocod6_fdc{ get; set; }
    public string ocod7_fdc{ get; set; }
    public string dlmp_mo_fdc{ get; set; }
    public string dlmp_dy_fdc{ get; set; }
    public string dlmp_yr_fdc{ get; set; }
    public string dofp_mo_fdc{ get; set; }
    public string dofp_dy_fdc{ get; set; }
    public string dofp_yr_fdc{ get; set; }
    public string dolp_mo_fdc{ get; set; }
    public string dolp_dy_fdc{ get; set; }
    public string dolp_yr_fdc{ get; set; }
    public string nprev_fdc{ get; set; }
    public string plbl_fdc{ get; set; }
    public string plbd_fdc{ get; set; }
    public string popo_fdc{ get; set; }
    public string mllb_fdc{ get; set; }
    public string yllb_fdc{ get; set; }
    public string mopo_fdc{ get; set; }
    public string yopo_fdc{ get; set; }
    public string cigpn_fdc{ get; set; }
    public string cigfn_fdc{ get; set; }
    public string cigsn_fdc{ get; set; }
    public string cigln_fdc{ get; set; }
    public string pdiab_fdc{ get; set; }
    public string gdiab_fdc{ get; set; }
    public string phype_fdc{ get; set; }
    public string ghype_fdc{ get; set; }
    public string ppb_fdc{ get; set; }
    public string ppo_fdc{ get; set; }
    public string inft_fdc{ get; set; }
    public string pces_fdc{ get; set; }
    public string npces_fdc{ get; set; }
    public string ehype_fdc{ get; set; }
    public string inft_drg_fdc{ get; set; }
    public string inft_art_fdc{ get; set; }
    public string citytxt_fdc{ get; set; }
    public string countytxt_fdc{ get; set; }
    public string statetxt_fdc{ get; set; }
    public string zipcode_fdc{ get; set; }
    public string mbplace_st_ter_txt_fdc{ get; set; }
    public string mbplace_cntry_txt_fdc{ get; set; }
    public string mager_fdc{ get; set; }
    public string mdob_mo_fdc{ get; set; }
    public string mdob_dy_fdc{ get; set; }
    public string mdob_yr_fdc{ get; set; }
    public string marn_fdc{ get; set; }
    public string meduc_fdc{ get; set; }
    public string mom_in_t_fdc{ get; set; }
    public string mom_oc_t_fdc{ get; set; }
    public string methnic1_fdc{ get; set; }
    public string methnic2_fdc{ get; set; }
    public string methnic3_fdc{ get; set; }
    public string methnic4_fdc{ get; set; }
    public string methnic5_fdc{ get; set; }
    public string mrace1_fdc{ get; set; }
    public string mrace2_fdc{ get; set; }
    public string mrace3_fdc{ get; set; }
    public string mrace4_fdc{ get; set; }
    public string mrace5_fdc{ get; set; }
    public string mrace6_fdc{ get; set; }
    public string mrace7_fdc{ get; set; }
    public string mrace8_fdc{ get; set; }
    public string mrace9_fdc{ get; set; }
    public string mrace10_fdc{ get; set; }
    public string mrace11_fdc{ get; set; }
    public string mrace12_fdc{ get; set; }
    public string mrace13_fdc{ get; set; }
    public string mrace14_fdc{ get; set; }
    public string mrace15_fdc{ get; set; }
    public string mrace16_fdc{ get; set; }
    public string mrace17_fdc{ get; set; }
    public string mrace18_fdc{ get; set; }
    public string mrace19_fdc{ get; set; }
    public string mrace20_fdc{ get; set; }
    public string mrace21_fdc{ get; set; }
    public string mrace22_fdc{ get; set; }
    public string mrace23_fdc{ get; set; }
    public string fager_fdc{ get; set; }
    public string dad_in_t_fdc{ get; set; }
    public string dad_oc_t_fdc{ get; set; }
    public string fbplacd_st_ter_c_fdc{ get; set; }
    public string fbplace_cnt_c_fdc{ get; set; }

}