using System;
using System.Collections.Generic;
using System.Collections.Immutable;

namespace mmria_pmss_client.Models.IJE;
public sealed class PMSS_Other_CSV_Mapping: TinyCsvParser.Mapping.CsvMapping<PMSS_Other>
{
    public PMSS_Other_CSV_Mapping()
        : base()
    {
        //MapProperty(0, x => x.environment);
            MapProperty(0, x => x.batch_name);
            MapProperty(1, x => x.fileno_dc);
            MapProperty(2, x => x.fileno_bc);
            MapProperty(3, x => x.fileno_fdc);
            MapProperty(4, x => x.year_birthorfetaldeath);
            MapProperty(5, x => x.pregcb_match);
            MapProperty(6, x => x.literalcod_match);
            MapProperty(7, x => x.icd10_match);
            MapProperty(8, x => x.bc_det_match);
            MapProperty(9, x => x.fdc_det_match);
            MapProperty(10, x => x.bc_prob_match);
            MapProperty(11, x => x.fdc_prob_match);
            MapProperty(12, x => x.vro_resolution_status);
            MapProperty(13, x => x.vro_resolution_remarks);
            MapProperty(14, x => x.Year);
            MapProperty(15, x => x.CaseNo);
            MapProperty(16, x => x.PMSS_State_Code);
            //MapProperty(, x => x.Jurisdiction	NOT MAPPED");
            //MapProperty(, x => x.Jurisdiction_Name	NOT MAPPED");
            MapProperty(17, x => x.Status);
            MapProperty(18, x => x.AmssNo);
            MapProperty(19, x => x.AmssRel);
            MapProperty(20, x => x.Dc);
            MapProperty(21, x => x.Dod);
            MapProperty(22, x => x.SourcNot);
            MapProperty(23, x => x.DcFile);
            MapProperty(24, x => x.LbFile);
            MapProperty(25, x => x.PregStat);
            MapProperty(26, x => x.PcbTime);
            MapProperty(27, x => x.StatDth);
            MapProperty(28, x => x.StatRes);
            MapProperty(29, x => x.ResZip);
            MapProperty(30, x => x.ZipSrce);
            MapProperty(31, x => x.County);
            MapProperty(32, x => x.CntySrce);
            MapProperty(33, x => x.MAge);
            MapProperty(34, x => x.Dob);
            MapProperty(35, x => x.AgeDif);
            MapProperty(36, x => x.Race);
            MapProperty(37, x => x.Race_Oth);
            MapProperty(38, x => x.Race_Source);
            MapProperty(39, x => x.Race_OMB);
            MapProperty(40, x => x.Race_White);
            MapProperty(41, x => x.Race_Black);
            MapProperty(42, x => x.Race_AmIndAlkNat);
            MapProperty(43, x => x.Race_AsianIndian);
            MapProperty(44, x => x.Race_Chinese);
            MapProperty(45, x => x.Race_Filipino);
            MapProperty(46, x => x.Race_Japanese);
            MapProperty(47, x => x.Race_Korean);
            MapProperty(48, x => x.Race_Vietnamese);
            MapProperty(49, x => x.Race_OtherAsian);
            MapProperty(50, x => x.Race_NativeHawaiian);
            MapProperty(51, x => x.Race_GuamCham);
            MapProperty(52, x => x.Race_Samoan);
            MapProperty(53, x => x.Race_OtherPacific);
            MapProperty(54, x => x.Race_Other);
            MapProperty(55, x => x.Race_NotSpecified);
            MapProperty(56, x => x.HispOrg);
            MapProperty(57, x => x.Hisp_Oth);
            MapProperty(58, x => x.MatBplc);
            MapProperty(59, x => x.MatBplc_US);
            MapProperty(60, x => x.MatBplc_Else);
            MapProperty(61, x => x.MarStat);
            MapProperty(62, x => x.EducaTn);
            MapProperty(63, x => x.PlaceDth);
            MapProperty(64, x => x.Pnc);
            MapProperty(65, x => x.Autopsy3);
            MapProperty(66, x => x.Height);
            MapProperty(67, x => x.WtPrePrg);
            MapProperty(68, x => x.PrevLb);
            MapProperty(69, x => x.PrvOthPg);
            MapProperty(70, x => x.PymtSrc);
            MapProperty(71, x => x.Wic);
            MapProperty(72, x => x.OutIndx);
            MapProperty(73, x => x.MultGest);
            MapProperty(74, x => x.TermProc);
            MapProperty(75, x => x.TermPro1);
            MapProperty(76, x => x.TermPro2);
            MapProperty(77, x => x.GestWk);
            MapProperty(78, x => x.DTerm);
            MapProperty(79, x => x.DayDif);
            MapProperty(80, x => x.CdcCod);
            MapProperty(81, x => x.Cod);
            MapProperty(82, x => x.AssoC1);
            MapProperty(83, x => x.Acon1);
            MapProperty(84, x => x.AssoC2);
            MapProperty(85, x => x.Acon2);
            MapProperty(86, x => x.AssoC3);
            MapProperty(87, x => x.Acon3);
            MapProperty(88, x => x.Injury);
            MapProperty(89, x => x.Drug_1);
            MapProperty(90, x => x.Drug_2);
            MapProperty(91, x => x.Drug_3);
            MapProperty(92, x => x.Class);
            MapProperty(93, x => x.Coder);
            MapProperty(94, x => x.ClsMo);
            MapProperty(95, x => x.ClsYr);
            MapProperty(96, x => x.Tribe);
            MapProperty(97, x => x.Occup);
            MapProperty(98, x => x.Indust);
            MapProperty(99, x => x.Bmi);
            MapProperty(100, x => x.Ethnic_Mexican);
            MapProperty(101, x => x.Ethnic_PR);
            MapProperty(102, x => x.Ethnic_Cuban);
            MapProperty(103, x => x.Ethnic_Other);
            MapProperty(104, x => x.Drug_IV);
            MapProperty(105, x => x.Dod_MO);
            MapProperty(106, x => x.Dod_DY);
            MapProperty(107, x => x.Dod_YR);
            MapProperty(108, x => x.Dod_TM);
            MapProperty(109, x => x.Dob_MO);
            MapProperty(110, x => x.Dob_DY);
            MapProperty(111, x => x.Dob_YR);
            MapProperty(112, x => x.DTerm_MO);
            MapProperty(113, x => x.DTerm_DY);
            MapProperty(114, x => x.DTerm_YR);
            MapProperty(115, x => x.DTerm_TM);
            MapProperty(116, x => x.Review_1_By);
            MapProperty(117, x => x.Review_1_On);
            MapProperty(118, x => x.Review_1_Remarks);
            MapProperty(119, x => x.Remarks);
            MapProperty(110, x => x.Update_Remarks);
            MapProperty(121, x => x.Pdf_Link);
            MapProperty(122, x => x.Pdf_Steve_Link);
            MapProperty(123, x => x.Review_2_By);
            MapProperty(124, x => x.Review_2_On);
            MapProperty(125, x => x.Review_2_Remarks);
            MapProperty(126, x => x.dc_info_complete);
            MapProperty(127, x => x.dc_info_remarks);
            MapProperty(128, x => x.mmria_used);
            MapProperty(129, x => x.mmria_used_remarks);
            MapProperty(130, x => x.agreement_status);
            MapProperty(131, x => x.agreement_remarks);
            MapProperty(132, x => x.transprt_dc);
            MapProperty(133, x => x.manner_dc);
            MapProperty(134, x => x.cod1a_dc);
            MapProperty(135, x => x.interval1a_dc);
            MapProperty(136, x => x.cod1b_dc);
            MapProperty(137, x => x.interval1b_dc);
            MapProperty(138, x => x.cod1c_dc);
            MapProperty(139, x => x.interval1c_dc);
            MapProperty(140, x => x.cod1d_dc);
            MapProperty(141, x => x.interval1d_dc);
            MapProperty(142, x => x.othercondition_dc);
            MapProperty(143, x => x.man_uc_dc);
            MapProperty(144, x => x.acme_uc_dc);
            MapProperty(145, x => x.eac_dc);
            MapProperty(146, x => x.rac_dc);
            MapProperty(147, x => x.howinj_dc);




    }




}