# Build runtime image
#FROM imagehub.cdc.gov:5989/rhel7/rhel:latest
#FROM  alpine:3.7
FROM imagehub.cdc.gov:5990/ahb/rhel-minimal:7.7


RUN mkdir /home/net_core_user
RUN mkdir /home/net_core_user/app

COPY ./app/mmria/mmria-server/bin/Debug/netcoreapp2.1/rhel.7-x64/publish /home/net_core_user/app/
COPY appsettings.json /home/net_core_user/app/

#COPY ./app/mmria/mmria-server/database-scripts/metadata_design_auth.json /home/net_core_user/app/database-scripts/metadata_design_auth.json
#COPY ./app/mmria/mmria-server/database-scripts/metadata.json /home/net_core_user/app/database-scripts/metadata.json
#COPY ./app/mmria/mmria-server/database-scripts/MMRIA_calculations.js /home/net_core_user/app/database-scripts/MMRIA_calculations.js
#COPY ./app/mmria/mmria-server/database-scripts/mmria-check-code.js /home/net_core_user/app/database-scripts/mmria-check-code.js
#COPY ./app/mmria/mmria-server/database-scripts/case_design_sortable.json /home/net_core_user/app/database-scripts/case_design_sortable.json
#COPY ./app/mmria/mmria-server/database-scripts/case_store_design_auth.json /home/net_core_user/app/database-scripts/case_store_design_auth.json
#COPY ./app/mmria/mmria-server/database-scripts/de-identified-list.json /home/net_core_user/app/database-scripts/de-identified-list.json
#COPY ./app/mmria/mmria-server/database-scripts/jurisdiction_design_auth.json /home/net_core_user/app/database-scripts/jurisdiction_design_auth.json
#COPY ./app/mmria/mmria-server/database-scripts/jurisdiction_sortable.json /home/net_core_user/app/database-scripts/jurisdiction_sortable.json


RUN mkdir /home/net_core_user/app/workdir

ENV HOME /home/net_core_user/app
WORKDIR /home/net_core_user/app

# Expose port 80 for the application.
EXPOSE 8080
USER 1001
ENTRYPOINT ["/home/net_core_user/app/mmria-server"]
