mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb AutopsyReport > AutopsyReport.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb ChildBirthCertificate > ChildBirthCertificate.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb CommitteeReview > CommitteeReview.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb DeathCertificate > DeathCertificate.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization > Hospitalization.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Interviews > Interviews.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb MaternalBirthCertificate > MaternalBirthCertificate.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb MaternalMortality > MaternalMortality.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits > OfficeVisits.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord > PrenatalCareRecord.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord > SocialServicesRecord.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb AutopsyReport11 > AutopsyReport11.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb AutopsyReport12 > AutopsyReport12.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb ChildBirthCertificate10 > ChildBirthCertificate10.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb ChildBirthCertificate9 > ChildBirthCertificate9.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb CommitteeReview28 > CommitteeReview28.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb CommitteeReview29 > CommitteeReview29.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb DeathCertificate2 > DeathCertificate2.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb DeathCertificate3 > DeathCertificate3.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb DeathCertificate4 > DeathCertificate4.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization20 > Hospitalization20.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization21 > Hospitalization21.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization22 > Hospitalization22.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization23 > Hospitalization23.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization24 > Hospitalization24.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Interviews30 > Interviews30.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb MaternalBirthCertificate5 > MaternalBirthCertificate5.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb MaternalBirthCertificate6 > MaternalBirthCertificate6.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb MaternalBirthCertificate7 > MaternalBirthCertificate7.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb MaternalBirthCertificate8 > MaternalBirthCertificate8.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb MaternalMortality1 > MaternalMortality1.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits25 > OfficeVisits25.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits26 > OfficeVisits26.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits27 > OfficeVisits27.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord13 > PrenatalCareRecord13.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord14 > PrenatalCareRecord14.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord15 > PrenatalCareRecord15.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord16 > PrenatalCareRecord16.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord17 > SocialServicesRecord17.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord18 > SocialServicesRecord18.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord19 > SocialServicesRecord19.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb AutopsyReport12AR_COD_grid > AutopsyReport12AR_COD_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb AutopsyReport11AR_Gross_grid > AutopsyReport11AR_Gross_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb AutopsyReport11AR_Micro_grid > AutopsyReport11AR_Micro_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb AutopsyReport12AR_Tox_Grid > AutopsyReport12AR_Tox_Grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb ChildBirthCertificate10PO_CoFD_grid > ChildBirthCertificate10PO_CoFD_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb CommitteeReview28CR_CDCICDMM_grd > CommitteeReview28CR_CDCICDMM_grd.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb CommitteeReview28CR_CoD_grid > CommitteeReview28CR_CoD_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb CommitteeReview29CR_FactAct_grid > CommitteeReview29CR_FactAct_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb DeathCertificate4DC_CoD_grid > DeathCertificate4DC_CoD_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization22MR_Anesth_grid > Hospitalization22MR_Anesth_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization22MR_BA_grid > Hospitalization22MR_BA_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization23MR_BB_grid > Hospitalization23MR_BB_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization20MR_ITran_grid > Hospitalization20MR_ITran_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization21MR_Lab_grid > Hospitalization21MR_Lab_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization23MR_Meds_grid > Hospitalization23MR_Meds_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization21MR_MExam_grid > Hospitalization21MR_MExam_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization21MR_Path_grid > Hospitalization21MR_Path_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization21MR_PExam_grid > Hospitalization21MR_PExam_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization24MR_RF_grid > Hospitalization24MR_RF_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization23MR_Surg_grid > Hospitalization23MR_Surg_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization23MR_Techn_grid > Hospitalization23MR_Techn_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb Hospitalization22MR_Vitalsigns_grid > Hospitalization22MR_Vitalsigns_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits25MV_FamHist_grid > OfficeVisits25MV_FamHist_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits26MV_Lab_grid > OfficeVisits26MV_Lab_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits25MV_MedHist_grid > OfficeVisits25MV_MedHist_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits27MV_Meds_grid > OfficeVisits27MV_Meds_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits26MV_PE_grid > OfficeVisits26MV_PE_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits27MV_RF_grid > OfficeVisits27MV_RF_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits25MV_SocHist_grid > OfficeVisits25MV_SocHist_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits26MV_Techn_grid > OfficeVisits26MV_Techn_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits26MV_Vitalsigns_grid > OfficeVisits26MV_Vitalsigns_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb OfficeVisits27MV_VSum_grid > OfficeVisits27MV_VSum_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord13PC_FamHist_grid > PrenatalCareRecord13PC_FamHist_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord16PC_HospER_grid > PrenatalCareRecord16PC_HospER_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord13PC_MedHist_grid > PrenatalCareRecord13PC_MedHist_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord16PC_Meds_grid > PrenatalCareRecord16PC_Meds_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord15PC_OthrTest_Grid > PrenatalCareRecord15PC_OthrTest_Grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord14PC_PgHist_grid > PrenatalCareRecord14PC_PgHist_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord15PC_PgProb_Grid > PrenatalCareRecord15PC_PgProb_Grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord15PC_PgProc_Grid > PrenatalCareRecord15PC_PgProc_Grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord16PC_Referrals_Grid > PrenatalCareRecord16PC_Referrals_Grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord15PC_RMonitor_grid > PrenatalCareRecord15PC_RMonitor_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord16PC_Source_grid > PrenatalCareRecord16PC_Source_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord13PC_SubAb_grid > PrenatalCareRecord13PC_SubAb_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb PrenatalCareRecord13PC_SurgProc_Grid > PrenatalCareRecord13PC_SurgProc_Grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord17SS_HH_grid > SocialServicesRecord17SS_HH_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord17SS_Jail_grid > SocialServicesRecord17SS_Jail_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord18SS_Refer_grid > SocialServicesRecord18SS_Refer_grid.csv
mdb-export /vagrant/source-code/scratch/owin/mmrds-importer/mapping-file-set/Maternal_Mortality.mdb SocialServicesRecord18SS_Sources_grid > SocialServicesRecord18SS_Sources_grid.csv


