//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.0.20.0 (Newtonsoft.Json v10.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace AwesomeSauce.v1
{
    

}